// Generated by penv 1.0.0-test from .env.schema. Do not edit.

package config;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/** Every variable .env.schema declares. {@code Env.load()} reads and checks them. */
public record Env(
        Secret apiToken,
        String homepage,
        Secret contact) {

    /** A value that prints as [redacted]; {@code expose()} returns it. */
    public static final class Secret {
        private final String value;

        public Secret(String value) {
            this.value = value;
        }

        public String expose() {
            return value;
        }

        @Override
        public String toString() {
            return "[redacted]";
        }
    }

    private static String raw(String name, String fallback, boolean required, List<String> problems) {
        String value = System.getenv(name);
        if (value == null || value.isEmpty()) {
            value = fallback;
        }
        if (value == null || value.isEmpty()) {
            if (required) {
                problems.add(name + " is not set; run penv check");
            }
            return null;
        }
        return value;
    }

    private static Boolean flag(String value) {
        switch (value.trim().toLowerCase()) {
            case "1": case "true": case "yes": case "on": return Boolean.TRUE;
            case "0": case "false": case "no": case "off": return Boolean.FALSE;
            default: return null;
        }
    }

    /** Read and check every variable. The exception names each problem, never a value. */
    public static Env load() {
        List<String> __penvProblems = new ArrayList<>();
        String __penvRaw_apiToken = raw("API_TOKEN", "", true, __penvProblems);
        Secret apiToken = __penvRaw_apiToken == null ? null : new Secret(__penvRaw_apiToken);
        String __penvRaw_homepage = raw("HOMEPAGE", "https://example.test", false, __penvProblems);
        String homepage = __penvRaw_homepage;
        String __penvRaw_contact = raw("CONTACT", "", false, __penvProblems);
        Secret contact = __penvRaw_contact == null ? null : new Secret(__penvRaw_contact);
        if (!__penvProblems.isEmpty()) {
            throw new IllegalStateException(String.join("; ", __penvProblems));
        }
        return new Env(
                apiToken,
                homepage,
                contact);
    }
}
