<?php

// Generated by penv 1.0.0-test from .env.schema. Do not edit.

declare(strict_types=1);

namespace App;

/** A value that prints as [redacted]; expose() returns it. */
final class Secret implements \Stringable, \JsonSerializable
{
    public function __construct(private readonly string $value)
    {
    }

    public function expose(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return '[redacted]';
    }

    public function jsonSerialize(): string
    {
        return '[redacted]';
    }

    /** @return array<string, string> */
    public function __debugInfo(): array
    {
        return ['value' => '[redacted]'];
    }
}

/** Every variable .env.schema declares. Env::load() reads and checks them. */
final class Env
{
    public function __construct(
        public readonly Secret $apiToken,
        public readonly string $homepage,
        public readonly ?Secret $contact,
    ) {
    }

    /** Read and check every variable. The exception names each problem, never a value. */
    public static function load(): self
    {
        $__penvProblems = [];
        $__penvRaw = static function (string $name, string $default, bool $required) use (&$__penvProblems): ?string {
            $value = getenv($name);
            if ($value === false || $value === '') {
                $value = $_ENV[$name] ?? '';
            }
            if ($value === '') {
                $value = $default;
            }
            if ($value === '') {
                if ($required) {
                    $__penvProblems[] = "{$name} is not set; run penv check";
                }
                return null;
            }
            return $value;
        };
        $__penvBad = static function (string $name, string $want) use (&$__penvProblems): mixed {
            $__penvProblems[] = "{$name} is not {$want}";
            return null;
        };
        $apiToken = $__penvRaw('API_TOKEN', '', true);
        $apiToken = $apiToken === null ? null : new Secret($apiToken);
        $homepage = $__penvRaw('HOMEPAGE', 'https://example.test', false);
        $contact = $__penvRaw('CONTACT', '', false);
        $contact = $contact === null ? null : new Secret($contact);
        if ($__penvProblems !== []) {
            throw new \RuntimeException(implode('; ', $__penvProblems));
        }

        return new self(
            apiToken: $apiToken,
            homepage: $homepage,
            contact: $contact,
        );
    }
}
