//! Generated by penv 1.0.0-test from .env.schema. Do not edit.
//!
//! `Env::load()` reads and checks every variable .env.schema declares. A field
//! holding a secret has type `Secret`, which prints as `[redacted]`.

#![allow(dead_code)]

use std::fmt;

/// A value that prints as `[redacted]`; `expose` returns it.
#[derive(Clone, Default, PartialEq, Eq)]
pub struct Secret(String);

impl Secret {
    /// The secret itself.
    pub fn expose(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for Secret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("[redacted]")
    }
}

impl fmt::Display for Secret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("[redacted]")
    }
}

/// Every variable .env.schema declares.
#[derive(Debug, Clone)]
pub struct Env {
    pub api_token: Secret,
    pub homepage: String,
    pub contact: Option<Secret>,
}

impl Env {
    fn raw(name: &str, default: &str, required: bool, problems: &mut Vec<String>) -> Option<String> {
        let value = std::env::var(name).ok().filter(|v| !v.is_empty());
        let value = value.or_else(|| (!default.is_empty()).then(|| default.to_string()));
        if value.is_none() && required {
            problems.push(format!("{name} is not set; run penv check"));
        }
        value
    }

    fn parsed<T>(name: &str, want: &str, value: Option<String>, parse: impl Fn(&str) -> Option<T>, problems: &mut Vec<String>) -> Option<T> {
        let value = value?;
        let out = parse(&value);
        if out.is_none() {
            problems.push(format!("{name} is not {want}"));
        }
        out
    }

    fn flag(v: &str) -> Option<bool> {
        match v.trim().to_ascii_lowercase().as_str() {
            "1" | "true" | "yes" | "on" => Some(true),
            "0" | "false" | "no" | "off" => Some(false),
            _ => None,
        }
    }

    /// Read and check every variable. The error names each problem, never a value.
    pub fn load() -> Result<Env, String> {
        let mut __penv_problems: Vec<String> = Vec::new();
        let api_token = Self::raw("API_TOKEN", "", true, &mut __penv_problems);
        let api_token = api_token.map(Secret);
        let homepage = Self::raw("HOMEPAGE", "https://example.test", false, &mut __penv_problems);
        let contact = Self::raw("CONTACT", "", false, &mut __penv_problems);
        let contact = contact.map(Secret);
        if !__penv_problems.is_empty() {
            return Err(__penv_problems.join("; "));
        }
        Ok(Env {
            api_token: api_token.unwrap_or_default(),
            homepage: homepage.unwrap_or_default(),
            contact,
        })
    }
}
