// <auto-generated>
// Generated by penv 1.0.0-test from .env.schema. Do not edit.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace App;

/// <summary>A value that prints as [redacted]; <c>Expose()</c> returns it.</summary>
public sealed class Secret
{
    private readonly string _value;

    public Secret(string value) => _value = value;

    public string Expose() => _value;

    public override string ToString() => "[redacted]";
}

/// <summary>Every variable .env.schema declares. <c>Env.Load()</c> reads and checks them.</summary>
public sealed record Env()
{
    private static string? __PenvRaw(string name, string fallback, bool required, List<string> problems)
    {
        var value = global::System.Environment.GetEnvironmentVariable(name);
        if (string.IsNullOrEmpty(value))
        {
            value = fallback;
        }
        if (string.IsNullOrEmpty(value))
        {
            if (required)
            {
                problems.Add($"{name} is not set; run penv check");
            }
            return null;
        }
        return value;
    }

    private static bool? __PenvFlag(string value) => value.Trim().ToLowerInvariant() switch
    {
        "1" or "true" or "yes" or "on" => true,
        "0" or "false" or "no" or "off" => false,
        _ => null,
    };

    /// <summary>Read and check every variable. The exception names each problem, never a value.</summary>
    public static Env Load()
    {
        var __penvProblems = new List<string>();
        if (__penvProblems.Count > 0)
        {
            throw new global::System.InvalidOperationException(string.Join("; ", __penvProblems));
        }
        return new Env();
    }
}
