// Code generated by penv 1.0.0-test from .env.schema. DO NOT EDIT.

// Package env reads the variables .env.schema declares.
// A field holding a secret has type Secret, which prints as [redacted].
package env

import (
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// Secret is a value that prints as [redacted]; Value returns it.
type Secret string

// Value returns the secret itself.
func (s Secret) Value() string { return string(s) }

// String keeps the secret out of logs and fmt output.
func (s Secret) String() string { return "[redacted]" }

// GoString keeps the secret out of %#v.
func (s Secret) GoString() string { return "[redacted]" }

// Env is every variable .env.schema declares.
type Env struct {
}

// Load reads and checks every variable. The error names each problem and never a value.
func Load() (*Env, error) {
	var problems []string
	raw := func(name, def string, required bool) (string, bool) {
		v, ok := os.LookupEnv(name)
		if !ok || v == "" {
			v = def
		}
		if v == "" {
			if required {
				problems = append(problems, name+" is not set; run penv check")
			}
			return "", false
		}
		return v, true
	}
	bad := func(name, want string) { problems = append(problems, name+" is not "+want) }
	_, _ = raw, bad
	_ = strconv.Itoa
	_ = strings.ToLower
	e := &Env{}
	if len(problems) > 0 {
		return nil, errors.New(strings.Join(problems, "; "))
	}
	return e, nil
}

// MustLoad is Load, panicking on a problem: for main.
func MustLoad() *Env {
	e, err := Load()
	if err != nil {
		panic(fmt.Sprintf("env: %v", err))
	}
	return e
}
