# Generated by penv 1.0.0-test from .env.schema. Do not edit.

from __future__ import annotations

import os
from typing import Any, Callable, Literal


def _raw(name: str, default: str | None, required: bool, problems: list[str]) -> Any:
    value = os.environ.get(name)
    if value is None or value == "":
        value = default
    if value is None or value == "":
        if required:
            problems.append(f"{name} is not set; run penv check")
        return None
    return value


# The parse error is dropped, not chained: its message would carry the value.
def _parsed(name: str, value: str | None, parse: Callable[[str], Any], want: str, problems: list[str]) -> Any:
    if value is None:
        return None
    try:
        return parse(value)
    except (ValueError, TypeError):
        problems.append(f"{name} is not {want}")
        return None


def _port(raw: str) -> int:
    port = int(raw)
    if not 1 <= port <= 65535:
        raise ValueError("out of range")
    return port


def _flag(raw: str) -> bool:
    word = raw.strip().lower()
    if word in ("1", "true", "yes", "on"):
        return True
    if word in ("0", "false", "no", "off"):
        return False
    raise ValueError("not a boolean")


def _one_of(*members: str) -> Callable[[str], str]:
    def parse(raw: str) -> str:
        if raw not in members:
            raise ValueError("not a member")
        return raw

    return parse


class Env:
    """Every variable .env.schema declares, read and checked once. The error
    names each problem, never a value."""

    def __init__(self) -> None:
        problems: list[str] = []
        if problems:
            raise RuntimeError("; ".join(problems))


env = Env()