// Generated by penv 1.0.0-test from .env.schema. Do not edit.


export const env = {
};

export type Env = typeof env;

export const envSchema = {
  "~standard": {
    version: 1,
    vendor: "penv",
    validate: (_input: unknown) => {
      const issues: { message: string; path: [string] }[] = [];
      return issues.length > 0 ? { issues } : { value: env };
    },
  },
} as const;