// <auto-generated>
// Generated by penv 1.0.0-test from .env.schema. Do not edit.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace App;

/// <summary>A value that prints as [redacted]; <c>Expose()</c> returns it.</summary>
public sealed class Secret
{
    private readonly string _value;

    public Secret(string value) => _value = value;

    public string Expose() => _value;

    public override string ToString() => "[redacted]";
}

/// <summary>Every variable .env.schema declares. <c>Env.Load()</c> reads and checks them.</summary>
public sealed record Env(
    Secret? Type,
    Secret? Match,
    Secret? Problems,
    Secret? Default,
    Secret? Class,
    Secret? Load_,
    Secret? Raw,
    Secret? Bad,
    Secret? Flag,
    double? N,
    double? E,
    Secret? This,
    Secret? Self,
    Secret? ToString_,
    Secret? None,
    string Greeting,
    int Port)
{
    private static string? __PenvRaw(string name, string fallback, bool required, List<string> problems)
    {
        var value = global::System.Environment.GetEnvironmentVariable(name);
        if (string.IsNullOrEmpty(value))
        {
            value = fallback;
        }
        if (string.IsNullOrEmpty(value))
        {
            if (required)
            {
                problems.Add($"{name} is not set; run penv check");
            }
            return null;
        }
        return value;
    }

    private static bool? __PenvFlag(string value) => value.Trim().ToLowerInvariant() switch
    {
        "1" or "true" or "yes" or "on" => true,
        "0" or "false" or "no" or "off" => false,
        _ => null,
    };

    /// <summary>Read and check every variable. The exception names each problem, never a value.</summary>
    public static Env Load()
    {
        var __penvProblems = new List<string>();
        var __penvRaw_type = __PenvRaw("TYPE", "", false, __penvProblems);
        var type = __penvRaw_type == null ? null : new Secret(__penvRaw_type);
        var __penvRaw_match = __PenvRaw("MATCH", "", false, __penvProblems);
        var match = __penvRaw_match == null ? null : new Secret(__penvRaw_match);
        var __penvRaw_problems = __PenvRaw("PROBLEMS", "", false, __penvProblems);
        var problems = __penvRaw_problems == null ? null : new Secret(__penvRaw_problems);
        var __penvRaw_default = __PenvRaw("DEFAULT", "", false, __penvProblems);
        var @default = __penvRaw_default == null ? null : new Secret(__penvRaw_default);
        var __penvRaw_class = __PenvRaw("CLASS", "", false, __penvProblems);
        var @class = __penvRaw_class == null ? null : new Secret(__penvRaw_class);
        var __penvRaw_load = __PenvRaw("LOAD", "", false, __penvProblems);
        var load = __penvRaw_load == null ? null : new Secret(__penvRaw_load);
        var __penvRaw_raw = __PenvRaw("RAW", "", false, __penvProblems);
        var raw = __penvRaw_raw == null ? null : new Secret(__penvRaw_raw);
        var __penvRaw_bad = __PenvRaw("BAD", "", false, __penvProblems);
        var bad = __penvRaw_bad == null ? null : new Secret(__penvRaw_bad);
        var __penvRaw_flag = __PenvRaw("FLAG", "", false, __penvProblems);
        var flag = __penvRaw_flag == null ? null : new Secret(__penvRaw_flag);
        var __penvRaw_n = __PenvRaw("N", "", false, __penvProblems);
        double? n = null;
        if (__penvRaw_n != null)
        {
            if (double.TryParse(__penvRaw_n.Trim(), global::System.Globalization.NumberStyles.Float, global::System.Globalization.CultureInfo.InvariantCulture, out var __penvN)) n = __penvN;
            else __penvProblems.Add("N" + " is not a number");
        }
        var __penvRaw_e = __PenvRaw("E", "", false, __penvProblems);
        double? e = null;
        if (__penvRaw_e != null)
        {
            if (double.TryParse(__penvRaw_e.Trim(), global::System.Globalization.NumberStyles.Float, global::System.Globalization.CultureInfo.InvariantCulture, out var __penvN)) e = __penvN;
            else __penvProblems.Add("E" + " is not a number");
        }
        var __penvRaw_this = __PenvRaw("THIS", "", false, __penvProblems);
        var @this = __penvRaw_this == null ? null : new Secret(__penvRaw_this);
        var __penvRaw_self = __PenvRaw("SELF", "", false, __penvProblems);
        var self = __penvRaw_self == null ? null : new Secret(__penvRaw_self);
        var __penvRaw_toString = __PenvRaw("TO_STRING", "", false, __penvProblems);
        var toString = __penvRaw_toString == null ? null : new Secret(__penvRaw_toString);
        var __penvRaw_none = __PenvRaw("None", "", false, __penvProblems);
        var none = __penvRaw_none == null ? null : new Secret(__penvRaw_none);
        var __penvRaw_greeting = __PenvRaw("GREETING", "Hi $name, from C:\\users", false, __penvProblems);
        var greeting = __penvRaw_greeting;
        var __penvRaw_port = __PenvRaw("PORT", "3000", false, __penvProblems);
        int? port = null;
        if (__penvRaw_port != null)
        {
            if (int.TryParse(__penvRaw_port.Trim(), global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var __penvN) && __penvN >= 1 && __penvN <= 65535) port = __penvN;
            else __penvProblems.Add("PORT" + " is not a port");
        }
        if (__penvProblems.Count > 0)
        {
            throw new global::System.InvalidOperationException(string.Join("; ", __penvProblems));
        }
        return new Env(
            type,
            match,
            problems,
            @default,
            @class,
            load,
            raw,
            bad,
            flag,
            n,
            e,
            @this,
            self,
            toString,
            none,
            greeting!,
            port!.Value);
    }
}
