// Code generated by penv 1.0.0-test from .env.schema. DO NOT EDIT.

// Package env reads the variables .env.schema declares.
// A field holding a secret has type Secret, which prints as [redacted].
package env

import (
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// Secret is a value that prints as [redacted]; Value returns it.
type Secret string

// Value returns the secret itself.
func (s Secret) Value() string { return string(s) }

// String keeps the secret out of logs and fmt output.
func (s Secret) String() string { return "[redacted]" }

// GoString keeps the secret out of %#v.
func (s Secret) GoString() string { return "[redacted]" }

// Env is every variable .env.schema declares.
type Env struct {
	// Kept in C:\users\penv, never in */tmp.
	Type *Secret

	Match *Secret

	Problems *Secret

	Default *Secret

	Class *Secret

	Load *Secret

	Raw *Secret

	Bad *Secret

	Flag *Secret

	N *float64

	E *float64

	This *Secret

	Self *Secret

	ToString *Secret

	None *Secret

	Greeting string

	Port int
}

// Load reads and checks every variable. The error names each problem and never a value.
func Load() (*Env, error) {
	var problems []string
	raw := func(name, def string, required bool) (string, bool) {
		v, ok := os.LookupEnv(name)
		if !ok || v == "" {
			v = def
		}
		if v == "" {
			if required {
				problems = append(problems, name+" is not set; run penv check")
			}
			return "", false
		}
		return v, true
	}
	bad := func(name, want string) { problems = append(problems, name+" is not "+want) }
	_, _ = raw, bad
	_ = strconv.Itoa
	_ = strings.ToLower
	e := &Env{}
	if v, ok := raw("TYPE", "", false); ok {
		s := Secret(v)
		e.Type = &s
	}
	if v, ok := raw("MATCH", "", false); ok {
		s := Secret(v)
		e.Match = &s
	}
	if v, ok := raw("PROBLEMS", "", false); ok {
		s := Secret(v)
		e.Problems = &s
	}
	if v, ok := raw("DEFAULT", "", false); ok {
		s := Secret(v)
		e.Default = &s
	}
	if v, ok := raw("CLASS", "", false); ok {
		s := Secret(v)
		e.Class = &s
	}
	if v, ok := raw("LOAD", "", false); ok {
		s := Secret(v)
		e.Load = &s
	}
	if v, ok := raw("RAW", "", false); ok {
		s := Secret(v)
		e.Raw = &s
	}
	if v, ok := raw("BAD", "", false); ok {
		s := Secret(v)
		e.Bad = &s
	}
	if v, ok := raw("FLAG", "", false); ok {
		s := Secret(v)
		e.Flag = &s
	}
	if v, ok := raw("N", "", false); ok {
		if n, err := strconv.ParseFloat(v, 64); err == nil {
			e.N = &n
		} else {
			bad("N", "a number")
		}
	}
	if v, ok := raw("E", "", false); ok {
		if n, err := strconv.ParseFloat(v, 64); err == nil {
			e.E = &n
		} else {
			bad("E", "a number")
		}
	}
	if v, ok := raw("THIS", "", false); ok {
		s := Secret(v)
		e.This = &s
	}
	if v, ok := raw("SELF", "", false); ok {
		s := Secret(v)
		e.Self = &s
	}
	if v, ok := raw("TO_STRING", "", false); ok {
		s := Secret(v)
		e.ToString = &s
	}
	if v, ok := raw("None", "", false); ok {
		s := Secret(v)
		e.None = &s
	}
	if v, ok := raw("GREETING", "Hi $name, from C:\\users", false); ok {
		s := string(v)
		e.Greeting = s
	}
	if v, ok := raw("PORT", "3000", false); ok {
		if n, err := strconv.Atoi(v); err == nil && n >= 1 && n <= 65535 {
			e.Port = n
		} else {
			bad("PORT", "a port")
		}
	}
	if len(problems) > 0 {
		return nil, errors.New(strings.Join(problems, "; "))
	}
	return e, nil
}

// MustLoad is Load, panicking on a problem: for main.
func MustLoad() *Env {
	e, err := Load()
	if err != nil {
		panic(fmt.Sprintf("env: %v", err))
	}
	return e
}
