// Generated by penv 1.0.0-test from .env.schema. Do not edit.

package config;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/** Every variable .env.schema declares. {@code Env.load()} reads and checks them. */
public record Env(
        /* Kept in C:\\users\penv, never in *\/tmp. */
        Secret type,
        Secret match,
        Secret problems,
        Secret default_,
        Secret class_,
        Secret load_,
        Secret raw,
        Secret bad,
        Secret flag,
        Double n,
        Double e,
        Secret this_,
        Secret self,
        Secret toString_,
        Secret none,
        String greeting,
        int port,
        Secret clone_) {

    /** A value that prints as [redacted]; {@code expose()} returns it. */
    public static final class Secret {
        private final String value;

        public Secret(String value) {
            this.value = value;
        }

        public String expose() {
            return value;
        }

        @Override
        public String toString() {
            return "[redacted]";
        }
    }

    private static String raw(String name, String fallback, boolean required, List<String> problems) {
        String value = System.getenv(name);
        if (value == null || value.isEmpty()) {
            value = fallback;
        }
        if (value == null || value.isEmpty()) {
            if (required) {
                problems.add(name + " is not set; run penv check");
            }
            return null;
        }
        return value;
    }

    private static Boolean flag(String value) {
        switch (value.trim().toLowerCase()) {
            case "1": case "true": case "yes": case "on": return Boolean.TRUE;
            case "0": case "false": case "no": case "off": return Boolean.FALSE;
            default: return null;
        }
    }

    /** Read and check every variable. The exception names each problem, never a value. */
    public static Env load() {
        List<String> __penvProblems = new ArrayList<>();
        String __penvRaw_type = raw("TYPE", "", false, __penvProblems);
        Secret type = __penvRaw_type == null ? null : new Secret(__penvRaw_type);
        String __penvRaw_match = raw("MATCH", "", false, __penvProblems);
        Secret match = __penvRaw_match == null ? null : new Secret(__penvRaw_match);
        String __penvRaw_problems = raw("PROBLEMS", "", false, __penvProblems);
        Secret problems = __penvRaw_problems == null ? null : new Secret(__penvRaw_problems);
        String __penvRaw_default = raw("DEFAULT", "", false, __penvProblems);
        Secret default_ = __penvRaw_default == null ? null : new Secret(__penvRaw_default);
        String __penvRaw_class = raw("CLASS", "", false, __penvProblems);
        Secret class_ = __penvRaw_class == null ? null : new Secret(__penvRaw_class);
        String __penvRaw_load = raw("LOAD", "", false, __penvProblems);
        Secret load_ = __penvRaw_load == null ? null : new Secret(__penvRaw_load);
        String __penvRaw_raw = raw("RAW", "", false, __penvProblems);
        Secret raw = __penvRaw_raw == null ? null : new Secret(__penvRaw_raw);
        String __penvRaw_bad = raw("BAD", "", false, __penvProblems);
        Secret bad = __penvRaw_bad == null ? null : new Secret(__penvRaw_bad);
        String __penvRaw_flag = raw("FLAG", "", false, __penvProblems);
        Secret flag = __penvRaw_flag == null ? null : new Secret(__penvRaw_flag);
        String __penvRaw_n = raw("N", "", false, __penvProblems);
        Double n = null;
        if (__penvRaw_n != null) {
            try {
                n = Double.parseDouble(__penvRaw_n.trim());
            } catch (NumberFormatException __penvE) {
                __penvProblems.add("N" + " is not a number");
            }
        }
        String __penvRaw_e = raw("E", "", false, __penvProblems);
        Double e = null;
        if (__penvRaw_e != null) {
            try {
                e = Double.parseDouble(__penvRaw_e.trim());
            } catch (NumberFormatException __penvE) {
                __penvProblems.add("E" + " is not a number");
            }
        }
        String __penvRaw_this = raw("THIS", "", false, __penvProblems);
        Secret this_ = __penvRaw_this == null ? null : new Secret(__penvRaw_this);
        String __penvRaw_self = raw("SELF", "", false, __penvProblems);
        Secret self = __penvRaw_self == null ? null : new Secret(__penvRaw_self);
        String __penvRaw_toString = raw("TO_STRING", "", false, __penvProblems);
        Secret toString_ = __penvRaw_toString == null ? null : new Secret(__penvRaw_toString);
        String __penvRaw_none = raw("None", "", false, __penvProblems);
        Secret none = __penvRaw_none == null ? null : new Secret(__penvRaw_none);
        String __penvRaw_greeting = raw("GREETING", "Hi $name, from C:\\users", false, __penvProblems);
        String greeting = __penvRaw_greeting;
        String __penvRaw_port = raw("PORT", "3000", false, __penvProblems);
        Integer port = null;
        if (__penvRaw_port != null) {
            try {
                int __penvN = Integer.parseInt(__penvRaw_port.trim());
                if (__penvN >= 1 && __penvN <= 65535) {
                    port = __penvN;
                } else {
                    __penvProblems.add("PORT" + " is not a port");
                }
            } catch (NumberFormatException __penvE) {
                __penvProblems.add("PORT" + " is not a port");
            }
        }
        String __penvRaw_clone = raw("CLONE", "", false, __penvProblems);
        Secret clone_ = __penvRaw_clone == null ? null : new Secret(__penvRaw_clone);
        if (!__penvProblems.isEmpty()) {
            throw new IllegalStateException(String.join("; ", __penvProblems));
        }
        return new Env(
                type,
                match,
                problems,
                default_,
                class_,
                load_,
                raw,
                bad,
                flag,
                n,
                e,
                this_,
                self,
                toString_,
                none,
                greeting,
                port,
                clone_);
    }
}
