<?php

// Generated by penv 1.0.0-test from .env.schema. Do not edit.

declare(strict_types=1);

namespace App;

/** A value that prints as [redacted]; expose() returns it. */
final class Secret implements \Stringable, \JsonSerializable
{
    public function __construct(private readonly string $value)
    {
    }

    public function expose(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return '[redacted]';
    }

    public function jsonSerialize(): string
    {
        return '[redacted]';
    }

    /** @return array<string, string> */
    public function __debugInfo(): array
    {
        return ['value' => '[redacted]'];
    }
}

/** Every variable .env.schema declares. Env::load() reads and checks them. */
final class Env
{
    public function __construct(
        /** Kept in C:\users\penv, never in *\/tmp. */
        public readonly ?Secret $type,
        public readonly ?Secret $match,
        public readonly ?Secret $problems,
        public readonly ?Secret $default,
        public readonly ?Secret $class,
        public readonly ?Secret $load,
        public readonly ?Secret $raw,
        public readonly ?Secret $bad,
        public readonly ?Secret $flag,
        public readonly ?float $n,
        public readonly ?float $e,
        public readonly ?Secret $this_,
        public readonly ?Secret $self,
        public readonly ?Secret $toString,
        public readonly ?Secret $none,
        public readonly string $greeting,
        public readonly int $port,
        public readonly ?Secret $clone,
    ) {
    }

    /** Read and check every variable. The exception names each problem, never a value. */
    public static function load(): self
    {
        $__penvProblems = [];
        $__penvRaw = static function (string $name, string $default, bool $required) use (&$__penvProblems): ?string {
            $value = getenv($name);
            if ($value === false || $value === '') {
                $value = $_ENV[$name] ?? '';
            }
            if ($value === '') {
                $value = $default;
            }
            if ($value === '') {
                if ($required) {
                    $__penvProblems[] = "{$name} is not set; run penv check";
                }
                return null;
            }
            return $value;
        };
        $__penvBad = static function (string $name, string $want) use (&$__penvProblems): mixed {
            $__penvProblems[] = "{$name} is not {$want}";
            return null;
        };
        $type = $__penvRaw('TYPE', '', false);
        $type = $type === null ? null : new Secret($type);
        $match = $__penvRaw('MATCH', '', false);
        $match = $match === null ? null : new Secret($match);
        $problems = $__penvRaw('PROBLEMS', '', false);
        $problems = $problems === null ? null : new Secret($problems);
        $default = $__penvRaw('DEFAULT', '', false);
        $default = $default === null ? null : new Secret($default);
        $class = $__penvRaw('CLASS', '', false);
        $class = $class === null ? null : new Secret($class);
        $load = $__penvRaw('LOAD', '', false);
        $load = $load === null ? null : new Secret($load);
        $raw = $__penvRaw('RAW', '', false);
        $raw = $raw === null ? null : new Secret($raw);
        $bad = $__penvRaw('BAD', '', false);
        $bad = $bad === null ? null : new Secret($bad);
        $flag = $__penvRaw('FLAG', '', false);
        $flag = $flag === null ? null : new Secret($flag);
        $n = $__penvRaw('N', '', false);
        if ($n !== null) {
            $__penvN = filter_var($n, FILTER_VALIDATE_FLOAT);
            $n = $__penvN === false ? $__penvBad('N', 'a number') : $__penvN;
        }
        $e = $__penvRaw('E', '', false);
        if ($e !== null) {
            $__penvN = filter_var($e, FILTER_VALIDATE_FLOAT);
            $e = $__penvN === false ? $__penvBad('E', 'a number') : $__penvN;
        }
        $this_ = $__penvRaw('THIS', '', false);
        $this_ = $this_ === null ? null : new Secret($this_);
        $self = $__penvRaw('SELF', '', false);
        $self = $self === null ? null : new Secret($self);
        $toString = $__penvRaw('TO_STRING', '', false);
        $toString = $toString === null ? null : new Secret($toString);
        $none = $__penvRaw('None', '', false);
        $none = $none === null ? null : new Secret($none);
        $greeting = $__penvRaw('GREETING', 'Hi $name, from C:\\users', false);
        $port = $__penvRaw('PORT', '3000', false);
        if ($port !== null) {
            $__penvN = filter_var($port, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1, 'max_range' => 65535]]);
            $port = $__penvN === false ? $__penvBad('PORT', 'a port') : $__penvN;
        }
        $clone = $__penvRaw('CLONE', '', false);
        $clone = $clone === null ? null : new Secret($clone);
        if ($__penvProblems !== []) {
            throw new \RuntimeException(implode('; ', $__penvProblems));
        }

        return new self(
            type: $type,
            match: $match,
            problems: $problems,
            default: $default,
            class: $class,
            load: $load,
            raw: $raw,
            bad: $bad,
            flag: $flag,
            n: $n,
            e: $e,
            this_: $this_,
            self: $self,
            toString: $toString,
            none: $none,
            greeting: $greeting,
            port: $port,
            clone: $clone,
        );
    }
}
