# Generated by penv 1.0.0-test from .env.schema. Do not edit.

from __future__ import annotations

import os
from typing import Any, Callable, Literal


def _raw(name: str, default: str | None, required: bool, problems: list[str]) -> Any:
    value = os.environ.get(name)
    if value is None or value == "":
        value = default
    if value is None or value == "":
        if required:
            problems.append(f"{name} is not set; run penv check")
        return None
    return value


# The parse error is dropped, not chained: its message would carry the value.
def _parsed(name: str, value: str | None, parse: Callable[[str], Any], want: str, problems: list[str]) -> Any:
    if value is None:
        return None
    try:
        return parse(value)
    except (ValueError, TypeError):
        problems.append(f"{name} is not {want}")
        return None


def _port(raw: str) -> int:
    port = int(raw)
    if not 1 <= port <= 65535:
        raise ValueError("out of range")
    return port


def _flag(raw: str) -> bool:
    word = raw.strip().lower()
    if word in ("1", "true", "yes", "on"):
        return True
    if word in ("0", "false", "no", "off"):
        return False
    raise ValueError("not a boolean")


def _one_of(*members: str) -> Callable[[str], str]:
    def parse(raw: str) -> str:
        if raw not in members:
            raise ValueError("not a member")
        return raw

    return parse


class Env:
    """Every variable .env.schema declares, read and checked once. The error
    names each problem, never a value."""

    def __init__(self) -> None:
        problems: list[str] = []
        # Kept in C:\users\penv, never in */tmp.
        self.TYPE: str | None = _raw("TYPE", None, False, problems)
        self.MATCH: str | None = _raw("MATCH", None, False, problems)
        self.PROBLEMS: str | None = _raw("PROBLEMS", None, False, problems)
        self.DEFAULT: str | None = _raw("DEFAULT", None, False, problems)
        self.CLASS: str | None = _raw("CLASS", None, False, problems)
        self.LOAD: str | None = _raw("LOAD", None, False, problems)
        self.RAW: str | None = _raw("RAW", None, False, problems)
        self.BAD: str | None = _raw("BAD", None, False, problems)
        self.FLAG: str | None = _raw("FLAG", None, False, problems)
        self.N: float | None = _parsed("N", _raw("N", None, False, problems), float, "a number", problems)
        self.E: float | None = _parsed("E", _raw("E", None, False, problems), float, "a number", problems)
        self.THIS: str | None = _raw("THIS", None, False, problems)
        self.SELF: str | None = _raw("SELF", None, False, problems)
        self.TO_STRING: str | None = _raw("TO_STRING", None, False, problems)
        self.None_: str | None = _raw("None", None, False, problems)
        self.GREETING: str = _raw("GREETING", "Hi $name, from C:\\users", False, problems)
        self.PORT: int = _parsed("PORT", _raw("PORT", "3000", False, problems), _port, "a port", problems)
        if problems:
            raise RuntimeError("; ".join(problems))


env = Env()