//! Generated by penv 1.0.0-test from .env.schema. Do not edit.
//!
//! `Env::load()` reads and checks every variable .env.schema declares. A field
//! holding a secret has type `Secret`, which prints as `[redacted]`.

#![allow(dead_code)]

use std::fmt;

/// A value that prints as `[redacted]`; `expose` returns it.
#[derive(Clone, Default, PartialEq, Eq)]
pub struct Secret(String);

impl Secret {
    /// The secret itself.
    pub fn expose(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for Secret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("[redacted]")
    }
}

impl fmt::Display for Secret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("[redacted]")
    }
}

/// Every variable .env.schema declares.
#[derive(Debug, Clone)]
pub struct Env {
    /// Kept in C:\users\penv, never in */tmp.
    pub r#type: Option<Secret>,
    pub r#match: Option<Secret>,
    pub problems: Option<Secret>,
    pub default: Option<Secret>,
    pub class: Option<Secret>,
    pub load: Option<Secret>,
    pub raw: Option<Secret>,
    pub bad: Option<Secret>,
    pub flag: Option<Secret>,
    pub n: Option<f64>,
    pub e: Option<f64>,
    pub this: Option<Secret>,
    pub self_: Option<Secret>,
    pub to_string: Option<Secret>,
    pub none: Option<Secret>,
    pub greeting: String,
    pub port: u16,
}

impl Env {
    fn raw(name: &str, default: &str, required: bool, problems: &mut Vec<String>) -> Option<String> {
        let value = std::env::var(name).ok().filter(|v| !v.is_empty());
        let value = value.or_else(|| (!default.is_empty()).then(|| default.to_string()));
        if value.is_none() && required {
            problems.push(format!("{name} is not set; run penv check"));
        }
        value
    }

    fn parsed<T>(name: &str, want: &str, value: Option<String>, parse: impl Fn(&str) -> Option<T>, problems: &mut Vec<String>) -> Option<T> {
        let value = value?;
        let out = parse(&value);
        if out.is_none() {
            problems.push(format!("{name} is not {want}"));
        }
        out
    }

    fn flag(v: &str) -> Option<bool> {
        match v.trim().to_ascii_lowercase().as_str() {
            "1" | "true" | "yes" | "on" => Some(true),
            "0" | "false" | "no" | "off" => Some(false),
            _ => None,
        }
    }

    /// Read and check every variable. The error names each problem, never a value.
    pub fn load() -> Result<Env, String> {
        let mut __penv_problems: Vec<String> = Vec::new();
        let r#type = Self::raw("TYPE", "", false, &mut __penv_problems);
        let r#type = r#type.map(Secret);
        let r#match = Self::raw("MATCH", "", false, &mut __penv_problems);
        let r#match = r#match.map(Secret);
        let problems = Self::raw("PROBLEMS", "", false, &mut __penv_problems);
        let problems = problems.map(Secret);
        let default = Self::raw("DEFAULT", "", false, &mut __penv_problems);
        let default = default.map(Secret);
        let class = Self::raw("CLASS", "", false, &mut __penv_problems);
        let class = class.map(Secret);
        let load = Self::raw("LOAD", "", false, &mut __penv_problems);
        let load = load.map(Secret);
        let raw = Self::raw("RAW", "", false, &mut __penv_problems);
        let raw = raw.map(Secret);
        let bad = Self::raw("BAD", "", false, &mut __penv_problems);
        let bad = bad.map(Secret);
        let flag = Self::raw("FLAG", "", false, &mut __penv_problems);
        let flag = flag.map(Secret);
        let n = Self::raw("N", "", false, &mut __penv_problems);
        let n = Self::parsed("N", "a number", n, |v| v.parse::<f64>().ok(), &mut __penv_problems);
        let e = Self::raw("E", "", false, &mut __penv_problems);
        let e = Self::parsed("E", "a number", e, |v| v.parse::<f64>().ok(), &mut __penv_problems);
        let this = Self::raw("THIS", "", false, &mut __penv_problems);
        let this = this.map(Secret);
        let self_ = Self::raw("SELF", "", false, &mut __penv_problems);
        let self_ = self_.map(Secret);
        let to_string = Self::raw("TO_STRING", "", false, &mut __penv_problems);
        let to_string = to_string.map(Secret);
        let none = Self::raw("None", "", false, &mut __penv_problems);
        let none = none.map(Secret);
        let greeting = Self::raw("GREETING", "Hi $name, from C:\\users", false, &mut __penv_problems);
        let port = Self::raw("PORT", "3000", false, &mut __penv_problems);
        let port = Self::parsed("PORT", "a port", port, |v| v.parse::<u16>().ok().filter(|p| *p > 0), &mut __penv_problems);
        if !__penv_problems.is_empty() {
            return Err(__penv_problems.join("; "));
        }
        Ok(Env {
            r#type,
            r#match,
            problems,
            default,
            class,
            load,
            raw,
            bad,
            flag,
            n,
            e,
            this,
            self_,
            to_string,
            none,
            greeting: greeting.unwrap_or_default(),
            port: port.unwrap_or_default(),
        })
    }
}
