// Generated by penv 1.0.0-test from .env.schema. Do not edit.

// Server keys are read here, by computed name, never as process.env.NAME: a
// bundler inlines only the literal form, so no build can copy these values into
// client code. In a runtime with no server environment (a browser) it throws.
const read = (name: string): string | undefined => {
  const g = globalThis as {
    process?: { env?: Record<string, string | undefined> };
    Deno?: { env: { get(name: string): string | undefined } };
    Netlify?: { env: { get(name: string): string | undefined } };
  };
  if (g.process?.env) return g.process.env[name];
  if (g.Deno?.env) return g.Deno.env.get(name);
  if (g.Netlify?.env) return g.Netlify.env.get(name);
  throw new Error(`${name} is server-only, and this runtime has no server environment.`);
};

// Masks this app's own secret values in what it logs and what it serves, in
// any server runtime (Node, Bun, Deno, edge, Workers), with no wrapper process:
// console methods (and any a log shipper installs later) and the Response
// constructor. Two characters kept, the rest replaced. Off with
// [targets.ts.options] mask = false.
(() => {
  const g = globalThis as { window?: unknown; __penvMask?: boolean; Response?: typeof Response };
  if (g.window !== undefined || g.__penvMask) return;
  let values: string[];
  try {
    values = [
      read("TYPE"),
      read("MATCH"),
      read("PROBLEMS"),
      read("DEFAULT"),
      read("CLASS"),
      read("LOAD"),
      read("RAW"),
      read("BAD"),
      read("FLAG"),
      read("N"),
      read("E"),
      read("THIS"),
      read("SELF"),
      read("TO_STRING"),
      read("None"),
      read("PORT"),
      read("CLONE"),
    ].filter((v): v is string => typeof v === "string" && v.length >= 4);
  } catch {
    return;
  }
  if (values.length === 0) return;
  g.__penvMask = true;
  const b64 = (v: string) => {
    try {
      return btoa(String.fromCharCode(...new TextEncoder().encode(v)));
    } catch {
      return "";
    }
  };
  const forms = [...new Set(values.flatMap((v) => [v, encodeURIComponent(v), b64(v), JSON.stringify(v).slice(1, -1)]))]
    .filter((f) => f.length >= 4)
    .sort((a, b) => b.length - a.length);
  const mask = (text: string) => {
    let out = text;
    for (const f of forms) if (out.includes(f)) out = out.split(f).join(f.slice(0, 2) + "*".repeat(f.length - 2));
    return out;
  };
  const maskArg = (a: unknown): unknown => {
    if (typeof a === "string") return mask(a);
    if (a && typeof a === "object") {
      try {
        const json = JSON.stringify(a);
        if (typeof json === "string" && mask(json) !== json) return mask(json);
      } catch {
        // not serialisable: printed as it is
      }
    }
    return a;
  };
  const guard = (fn: unknown) => {
    if (typeof fn !== "function" || (fn as { __penv?: boolean }).__penv) return fn;
    const wrapped = function (this: unknown, ...args: unknown[]) {
      return (fn as (...a: unknown[]) => unknown).apply(this, args.map(maskArg));
    };
    (wrapped as { __penv?: boolean }).__penv = true;
    return wrapped;
  };
  const target = console as unknown as Record<string, unknown>;
  for (const level of ["log", "info", "warn", "error", "debug", "trace"]) {
    let current = guard(target[level]);
    try {
      Object.defineProperty(console, level, {
        configurable: true,
        get: () => current,
        set: (fn: unknown) => {
          current = guard(fn);
        },
      });
    } catch {
      target[level] = current;
    }
  }
  const Original = g.Response;
  if (typeof Original === "function") {
    type Body = ConstructorParameters<typeof Response>[0];
    type Init = ConstructorParameters<typeof Response>[1];
    class Masked extends Original {
      constructor(body?: Body, init?: Init) {
        super(typeof body === "string" ? mask(body) : body, init);
      }
      static override json(data: unknown, init?: Init) {
        const headers = new Headers(init?.headers);
        if (!headers.has("content-type")) headers.set("content-type", "application/json");
        return new Masked(JSON.stringify(data), { ...init, headers });
      }
    }
    g.Response = Masked;
  }
})();

const given = (value: string | undefined, fallback: string): string =>
  value === undefined || value === "" ? fallback : value;

const maybe = <T,>(value: string | undefined, as: (v: string) => T): T | undefined =>
  value === undefined || value === "" ? undefined : as(value);

export const env = {
  /** Kept in C:\users\penv, never in *\/tmp. */
  get TYPE() {
    return read("TYPE") as string | undefined;
  },
  get MATCH() {
    return read("MATCH") as string | undefined;
  },
  get PROBLEMS() {
    return read("PROBLEMS") as string | undefined;
  },
  get DEFAULT() {
    return read("DEFAULT") as string | undefined;
  },
  get CLASS() {
    return read("CLASS") as string | undefined;
  },
  get LOAD() {
    return read("LOAD") as string | undefined;
  },
  get RAW() {
    return read("RAW") as string | undefined;
  },
  get BAD() {
    return read("BAD") as string | undefined;
  },
  get FLAG() {
    return read("FLAG") as string | undefined;
  },
  get N() {
    return maybe(read("N"), Number);
  },
  get E() {
    return maybe(read("E"), Number);
  },
  get THIS() {
    return read("THIS") as string | undefined;
  },
  get SELF() {
    return read("SELF") as string | undefined;
  },
  get TO_STRING() {
    return read("TO_STRING") as string | undefined;
  },
  get None() {
    return read("None") as string | undefined;
  },
  get GREETING() {
    return given(read("GREETING"), "Hi $name, from C:\\users") as string;
  },
  get PORT() {
    return Number(given(read("PORT"), "3000"));
  },
  get CLONE() {
    return read("CLONE") as string | undefined;
  },
};

export type Env = typeof env;

export const envSchema = {
  "~standard": {
    version: 1,
    vendor: "penv",
    validate: (input: unknown) => {
      const seen = (input ?? {}) as Record<string, unknown>;
      const issues: { message: string; path: [string] }[] = [];
      const is = {
        number: (v: string) => Number.isFinite(Number(v)),
        integer: (v: string) => Number.isInteger(Number(v)),
        port: (v: string) => Number.isInteger(Number(v)) && Number(v) >= 1 && Number(v) <= 65535,
      };
      if (seen["N"] !== undefined && seen["N"] !== "" && !is.number(String(seen["N"]))) {
        issues.push({ message: "N must be a number", path: ["N"] });
      }
      if (seen["E"] !== undefined && seen["E"] !== "" && !is.number(String(seen["E"]))) {
        issues.push({ message: "E must be a number", path: ["E"] });
      }
      if (seen["PORT"] !== undefined && seen["PORT"] !== "" && !is.port(String(seen["PORT"]))) {
        issues.push({ message: "PORT must be a port between 1 and 65535", path: ["PORT"] });
      }
      return issues.length > 0 ? { issues } : { value: env };
    },
  },
} as const;