// <auto-generated>
// Generated by penv 1.0.0-test from .env.schema. Do not edit.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;

namespace App;

/// <summary>A value that prints as [redacted]; <c>Expose()</c> returns it.</summary>
public sealed class Secret
{
    private readonly string _value;

    public Secret(string value) => _value = value;

    public string Expose() => _value;

    public override string ToString() => "[redacted]";
}

/// <summary>Every variable .env.schema declares. <c>Env.Load()</c> reads and checks them.</summary>
public sealed record Env(
    Secret DatabaseUrl,
    Secret StripeSecretKey,
    string NextPublicAppUrl,
    int Port,
    string NodeEnv,
    string PlanTier,
    double CacheTtlSeconds,
    long MaxRetries,
    bool FeatureBilling,
    bool DebugTracing,
    string AlertsEmail,
    Secret? SupportNote)
{
    private static string? Raw(string name, string fallback, bool required, List<string> problems)
    {
        var value = Environment.GetEnvironmentVariable(name);
        if (string.IsNullOrEmpty(value))
        {
            value = fallback;
        }
        if (string.IsNullOrEmpty(value))
        {
            if (required)
            {
                problems.Add($"{name} is not set; run penv check");
            }
            return null;
        }
        return value;
    }

    private static bool? Flag(string value) => value.Trim().ToLowerInvariant() switch
    {
        "1" or "true" or "yes" or "on" => true,
        "0" or "false" or "no" or "off" => false,
        _ => null,
    };

    /// <summary>Read and check every variable. The exception names each problem, never a value.</summary>
    public static Env Load()
    {
        var problems = new List<string>();
        var databaseUrlRaw = Raw("DATABASE_URL", "", true, problems);
        var databaseUrl = databaseUrlRaw == null ? null : new Secret(databaseUrlRaw);
        var stripeSecretKeyRaw = Raw("STRIPE_SECRET_KEY", "", true, problems);
        var stripeSecretKey = stripeSecretKeyRaw == null ? null : new Secret(stripeSecretKeyRaw);
        var nextPublicAppUrlRaw = Raw("NEXT_PUBLIC_APP_URL", "http://localhost:3000", false, problems);
        var nextPublicAppUrl = nextPublicAppUrlRaw;
        var portRaw = Raw("PORT", "3000", false, problems);
        int? port = null;
        if (portRaw != null)
        {
            if (int.TryParse(portRaw.Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var n) && n >= 1 && n <= 65535) port = n;
            else problems.Add("PORT" + " is not a port");
        }
        var nodeEnvRaw = Raw("NODE_ENV", "development", false, problems);
        var nodeEnv = nodeEnvRaw;
        if (nodeEnv != null && Array.IndexOf(new[] { "development", "staging", "production" }, nodeEnv) < 0)
        {
            problems.Add("NODE_ENV" + " is not one of development, staging, production");
            nodeEnv = null;
        }
        var planTierRaw = Raw("PLAN_TIER", "", true, problems);
        var planTier = planTierRaw;
        if (planTier != null && Array.IndexOf(new[] { "free", "pro", "enterprise" }, planTier) < 0)
        {
            problems.Add("PLAN_TIER" + " is not one of free, pro, enterprise");
            planTier = null;
        }
        var cacheTtlSecondsRaw = Raw("CACHE_TTL_SECONDS", "1.5", false, problems);
        double? cacheTtlSeconds = null;
        if (cacheTtlSecondsRaw != null)
        {
            if (double.TryParse(cacheTtlSecondsRaw.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var n)) cacheTtlSeconds = n;
            else problems.Add("CACHE_TTL_SECONDS" + " is not a number");
        }
        var maxRetriesRaw = Raw("MAX_RETRIES", "", true, problems);
        long? maxRetries = null;
        if (maxRetriesRaw != null)
        {
            if (long.TryParse(maxRetriesRaw.Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var n)) maxRetries = n;
            else problems.Add("MAX_RETRIES" + " is not an integer");
        }
        var featureBillingRaw = Raw("FEATURE_BILLING", "false", false, problems);
        bool? featureBilling = featureBillingRaw == null ? null : Flag(featureBillingRaw);
        if (featureBillingRaw != null && featureBilling == null) problems.Add("FEATURE_BILLING" + " is not a boolean");
        var debugTracingRaw = Raw("DEBUG_TRACING", "", true, problems);
        bool? debugTracing = debugTracingRaw == null ? null : Flag(debugTracingRaw);
        if (debugTracingRaw != null && debugTracing == null) problems.Add("DEBUG_TRACING" + " is not a boolean");
        var alertsEmailRaw = Raw("ALERTS_EMAIL", "ops@example.test", false, problems);
        var alertsEmail = alertsEmailRaw;
        var supportNoteRaw = Raw("SUPPORT_NOTE", "", false, problems);
        var supportNote = supportNoteRaw == null ? null : new Secret(supportNoteRaw);
        if (problems.Count > 0)
        {
            throw new InvalidOperationException(string.Join("; ", problems));
        }
        return new Env(
            databaseUrl!,
            stripeSecretKey!,
            nextPublicAppUrl!,
            port!.Value,
            nodeEnv!,
            planTier!,
            cacheTtlSeconds!.Value,
            maxRetries!.Value,
            featureBilling!.Value,
            debugTracing!.Value,
            alertsEmail!,
            supportNote);
    }
}
