// <auto-generated>
// Generated by penv 1.0.0-test from .env.schema. Do not edit.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace App;

/// <summary>A value that prints as [redacted]; <c>Expose()</c> returns it.</summary>
public sealed class Secret
{
    private readonly string _value;

    public Secret(string value) => _value = value;

    public string Expose() => _value;

    public override string ToString() => "[redacted]";
}

/// <summary>Every variable .env.schema declares. <c>Env.Load()</c> reads and checks them.</summary>
public sealed record Env(
    Secret DatabaseUrl,
    Secret StripeSecretKey,
    string NextPublicAppUrl,
    int Port,
    string NodeEnv,
    string PlanTier,
    double CacheTtlSeconds,
    long MaxRetries,
    bool FeatureBilling,
    bool DebugTracing,
    string AlertsEmail,
    Secret? SupportNote,
    Secret NextPublicCheckoutToken)
{
    private static string? __PenvRaw(string name, string fallback, bool required, List<string> problems)
    {
        var value = global::System.Environment.GetEnvironmentVariable(name);
        if (string.IsNullOrEmpty(value))
        {
            value = fallback;
        }
        if (string.IsNullOrEmpty(value))
        {
            if (required)
            {
                problems.Add($"{name} is not set; run penv check");
            }
            return null;
        }
        return value;
    }

    private static bool? __PenvFlag(string value) => value.Trim().ToLowerInvariant() switch
    {
        "1" or "true" or "yes" or "on" => true,
        "0" or "false" or "no" or "off" => false,
        _ => null,
    };

    /// <summary>Read and check every variable. The exception names each problem, never a value.</summary>
    public static Env Load()
    {
        var __penvProblems = new List<string>();
        var __penvRaw_databaseUrl = __PenvRaw("DATABASE_URL", "", true, __penvProblems);
        var databaseUrl = __penvRaw_databaseUrl == null ? null : new Secret(__penvRaw_databaseUrl);
        var __penvRaw_stripeSecretKey = __PenvRaw("STRIPE_SECRET_KEY", "", true, __penvProblems);
        var stripeSecretKey = __penvRaw_stripeSecretKey == null ? null : new Secret(__penvRaw_stripeSecretKey);
        var __penvRaw_nextPublicAppUrl = __PenvRaw("NEXT_PUBLIC_APP_URL", "http://localhost:3000", false, __penvProblems);
        var nextPublicAppUrl = __penvRaw_nextPublicAppUrl;
        var __penvRaw_port = __PenvRaw("PORT", "3000", false, __penvProblems);
        int? port = null;
        if (__penvRaw_port != null)
        {
            if (int.TryParse(__penvRaw_port.Trim(), global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var __penvN) && __penvN >= 1 && __penvN <= 65535) port = __penvN;
            else __penvProblems.Add("PORT" + " is not a port");
        }
        var __penvRaw_nodeEnv = __PenvRaw("NODE_ENV", "development", false, __penvProblems);
        var nodeEnv = __penvRaw_nodeEnv;
        if (nodeEnv != null && global::System.Array.IndexOf(new[] { "development", "staging", "production" }, nodeEnv) < 0)
        {
            __penvProblems.Add("NODE_ENV is not one of development, staging, production");
            nodeEnv = null;
        }
        var __penvRaw_planTier = __PenvRaw("PLAN_TIER", "", true, __penvProblems);
        var planTier = __penvRaw_planTier;
        if (planTier != null && global::System.Array.IndexOf(new[] { "free", "pro", "enterprise" }, planTier) < 0)
        {
            __penvProblems.Add("PLAN_TIER is not one of free, pro, enterprise");
            planTier = null;
        }
        var __penvRaw_cacheTtlSeconds = __PenvRaw("CACHE_TTL_SECONDS", "1.5", false, __penvProblems);
        double? cacheTtlSeconds = null;
        if (__penvRaw_cacheTtlSeconds != null)
        {
            if (double.TryParse(__penvRaw_cacheTtlSeconds.Trim(), global::System.Globalization.NumberStyles.Float, global::System.Globalization.CultureInfo.InvariantCulture, out var __penvN)) cacheTtlSeconds = __penvN;
            else __penvProblems.Add("CACHE_TTL_SECONDS" + " is not a number");
        }
        var __penvRaw_maxRetries = __PenvRaw("MAX_RETRIES", "", true, __penvProblems);
        long? maxRetries = null;
        if (__penvRaw_maxRetries != null)
        {
            if (long.TryParse(__penvRaw_maxRetries.Trim(), global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var __penvN)) maxRetries = __penvN;
            else __penvProblems.Add("MAX_RETRIES" + " is not an integer");
        }
        var __penvRaw_featureBilling = __PenvRaw("FEATURE_BILLING", "false", false, __penvProblems);
        bool? featureBilling = __penvRaw_featureBilling == null ? null : __PenvFlag(__penvRaw_featureBilling);
        if (__penvRaw_featureBilling != null && featureBilling == null) __penvProblems.Add("FEATURE_BILLING" + " is not a boolean");
        var __penvRaw_debugTracing = __PenvRaw("DEBUG_TRACING", "", true, __penvProblems);
        bool? debugTracing = __penvRaw_debugTracing == null ? null : __PenvFlag(__penvRaw_debugTracing);
        if (__penvRaw_debugTracing != null && debugTracing == null) __penvProblems.Add("DEBUG_TRACING" + " is not a boolean");
        var __penvRaw_alertsEmail = __PenvRaw("ALERTS_EMAIL", "ops@example.test", false, __penvProblems);
        var alertsEmail = __penvRaw_alertsEmail;
        var __penvRaw_supportNote = __PenvRaw("SUPPORT_NOTE", "", false, __penvProblems);
        var supportNote = __penvRaw_supportNote == null ? null : new Secret(__penvRaw_supportNote);
        var __penvRaw_nextPublicCheckoutToken = __PenvRaw("NEXT_PUBLIC_CHECKOUT_TOKEN", "", true, __penvProblems);
        var nextPublicCheckoutToken = __penvRaw_nextPublicCheckoutToken == null ? null : new Secret(__penvRaw_nextPublicCheckoutToken);
        if (__penvProblems.Count > 0)
        {
            throw new global::System.InvalidOperationException(string.Join("; ", __penvProblems));
        }
        return new Env(
            databaseUrl!,
            stripeSecretKey!,
            nextPublicAppUrl!,
            port!.Value,
            nodeEnv!,
            planTier!,
            cacheTtlSeconds!.Value,
            maxRetries!.Value,
            featureBilling!.Value,
            debugTracing!.Value,
            alertsEmail!,
            supportNote,
            nextPublicCheckoutToken!);
    }
}
