// Code generated by penv 1.0.0-test from .env.schema. DO NOT EDIT.

// Package env reads the variables .env.schema declares.
// A field holding a secret has type Secret, which prints as [redacted].
package env

import (
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// Secret is a value that prints as [redacted]; Value returns it.
type Secret string

// Value returns the secret itself.
func (s Secret) Value() string { return string(s) }

// String keeps the secret out of logs and fmt output.
func (s Secret) String() string { return "[redacted]" }

// GoString keeps the secret out of %#v.
func (s Secret) GoString() string { return "[redacted]" }

// Env is every variable .env.schema declares.
type Env struct {
	// Where the service keeps its own rows.
	DatabaseUrl Secret

	StripeSecretKey Secret

	// Where the browser is sent back to after a redirect.
	NextPublicAppUrl string

	Port int

	NodeEnv string

	// The tier this deployment serves.
	PlanTier string

	// How long a cached value stays fresh.
	CacheTtlSeconds float64

	MaxRetries int64

	FeatureBilling bool

	DebugTracing bool

	// Where failures are mailed.
	AlertsEmail string

	SupportNote *Secret

	// Built from the secret, so its prefix does not make it safe to inline.
	NextPublicCheckoutToken Secret
}

// Load reads and checks every variable. The error names each problem and never a value.
func Load() (*Env, error) {
	var problems []string
	raw := func(name, def string, required bool) (string, bool) {
		v, ok := os.LookupEnv(name)
		if !ok || v == "" {
			v = def
		}
		if v == "" {
			if required {
				problems = append(problems, name+" is not set; run penv check")
			}
			return "", false
		}
		return v, true
	}
	bad := func(name, want string) { problems = append(problems, name+" is not "+want) }
	_, _ = raw, bad
	_ = strconv.Itoa
	_ = strings.ToLower
	e := &Env{}
	if v, ok := raw("DATABASE_URL", "", true); ok {
		s := Secret(v)
		e.DatabaseUrl = s
	}
	if v, ok := raw("STRIPE_SECRET_KEY", "", true); ok {
		s := Secret(v)
		e.StripeSecretKey = s
	}
	if v, ok := raw("NEXT_PUBLIC_APP_URL", "http://localhost:3000", false); ok {
		s := string(v)
		e.NextPublicAppUrl = s
	}
	if v, ok := raw("PORT", "3000", false); ok {
		if n, err := strconv.Atoi(v); err == nil && n >= 1 && n <= 65535 {
			e.Port = n
		} else {
			bad("PORT", "a port")
		}
	}
	if v, ok := raw("NODE_ENV", "development", false); ok {
		switch v {
		case "development", "staging", "production":
			e.NodeEnv = v
		default:
			bad("NODE_ENV", "one of development, staging, production")
		}
	}
	if v, ok := raw("PLAN_TIER", "", true); ok {
		switch v {
		case "free", "pro", "enterprise":
			e.PlanTier = v
		default:
			bad("PLAN_TIER", "one of free, pro, enterprise")
		}
	}
	if v, ok := raw("CACHE_TTL_SECONDS", "1.5", false); ok {
		if n, err := strconv.ParseFloat(v, 64); err == nil {
			e.CacheTtlSeconds = n
		} else {
			bad("CACHE_TTL_SECONDS", "a number")
		}
	}
	if v, ok := raw("MAX_RETRIES", "", true); ok {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			e.MaxRetries = n
		} else {
			bad("MAX_RETRIES", "an integer")
		}
	}
	if v, ok := raw("FEATURE_BILLING", "false", false); ok {
		switch strings.ToLower(strings.TrimSpace(v)) {
		case "1", "true", "yes", "on":
			b := true
			e.FeatureBilling = b
		case "0", "false", "no", "off":
			b := false
			e.FeatureBilling = b
		default:
			bad("FEATURE_BILLING", "a boolean")
		}
	}
	if v, ok := raw("DEBUG_TRACING", "", true); ok {
		switch strings.ToLower(strings.TrimSpace(v)) {
		case "1", "true", "yes", "on":
			b := true
			e.DebugTracing = b
		case "0", "false", "no", "off":
			b := false
			e.DebugTracing = b
		default:
			bad("DEBUG_TRACING", "a boolean")
		}
	}
	if v, ok := raw("ALERTS_EMAIL", "ops@example.test", false); ok {
		s := string(v)
		e.AlertsEmail = s
	}
	if v, ok := raw("SUPPORT_NOTE", "", false); ok {
		s := Secret(v)
		e.SupportNote = &s
	}
	if v, ok := raw("NEXT_PUBLIC_CHECKOUT_TOKEN", "", true); ok {
		s := Secret(v)
		e.NextPublicCheckoutToken = s
	}
	if len(problems) > 0 {
		return nil, errors.New(strings.Join(problems, "; "))
	}
	return e, nil
}

// MustLoad is Load, panicking on a problem: for main.
func MustLoad() *Env {
	e, err := Load()
	if err != nil {
		panic(fmt.Sprintf("env: %v", err))
	}
	return e
}
