// Generated by penv 1.0.0-test from .env.schema. Do not edit.

package config;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/** Every variable .env.schema declares. {@code Env.load()} reads and checks them. */
public record Env(
        /* Where the service keeps its own rows. */
        Secret databaseUrl,
        Secret stripeSecretKey,
        /* Where the browser is sent back to after a redirect. */
        String nextPublicAppUrl,
        int port,
        String nodeEnv,
        /* The tier this deployment serves. */
        String planTier,
        /* How long a cached value stays fresh. */
        double cacheTtlSeconds,
        long maxRetries,
        boolean featureBilling,
        boolean debugTracing,
        /* Where failures are mailed. */
        String alertsEmail,
        Secret supportNote,
        /* Built from the secret, so its prefix does not make it safe to inline. */
        Secret nextPublicCheckoutToken) {

    /** A value that prints as [redacted]; {@code expose()} returns it. */
    public static final class Secret {
        private final String value;

        public Secret(String value) {
            this.value = value;
        }

        public String expose() {
            return value;
        }

        @Override
        public String toString() {
            return "[redacted]";
        }
    }

    private static String raw(String name, String fallback, boolean required, List<String> problems) {
        String value = System.getenv(name);
        if (value == null || value.isEmpty()) {
            value = fallback;
        }
        if (value == null || value.isEmpty()) {
            if (required) {
                problems.add(name + " is not set; run penv check");
            }
            return null;
        }
        return value;
    }

    private static Boolean flag(String value) {
        switch (value.trim().toLowerCase()) {
            case "1": case "true": case "yes": case "on": return Boolean.TRUE;
            case "0": case "false": case "no": case "off": return Boolean.FALSE;
            default: return null;
        }
    }

    /** Read and check every variable. The exception names each problem, never a value. */
    public static Env load() {
        List<String> __penvProblems = new ArrayList<>();
        String __penvRaw_databaseUrl = raw("DATABASE_URL", "", true, __penvProblems);
        Secret databaseUrl = __penvRaw_databaseUrl == null ? null : new Secret(__penvRaw_databaseUrl);
        String __penvRaw_stripeSecretKey = raw("STRIPE_SECRET_KEY", "", true, __penvProblems);
        Secret stripeSecretKey = __penvRaw_stripeSecretKey == null ? null : new Secret(__penvRaw_stripeSecretKey);
        String __penvRaw_nextPublicAppUrl = raw("NEXT_PUBLIC_APP_URL", "http://localhost:3000", false, __penvProblems);
        String nextPublicAppUrl = __penvRaw_nextPublicAppUrl;
        String __penvRaw_port = raw("PORT", "3000", false, __penvProblems);
        Integer port = null;
        if (__penvRaw_port != null) {
            try {
                int __penvN = Integer.parseInt(__penvRaw_port.trim());
                if (__penvN >= 1 && __penvN <= 65535) {
                    port = __penvN;
                } else {
                    __penvProblems.add("PORT" + " is not a port");
                }
            } catch (NumberFormatException __penvE) {
                __penvProblems.add("PORT" + " is not a port");
            }
        }
        String __penvRaw_nodeEnv = raw("NODE_ENV", "development", false, __penvProblems);
        String nodeEnv = __penvRaw_nodeEnv;
        if (nodeEnv != null && !Set.of("development", "staging", "production").contains(nodeEnv)) {
            __penvProblems.add("NODE_ENV is not one of development, staging, production");
            nodeEnv = null;
        }
        String __penvRaw_planTier = raw("PLAN_TIER", "", true, __penvProblems);
        String planTier = __penvRaw_planTier;
        if (planTier != null && !Set.of("free", "pro", "enterprise").contains(planTier)) {
            __penvProblems.add("PLAN_TIER is not one of free, pro, enterprise");
            planTier = null;
        }
        String __penvRaw_cacheTtlSeconds = raw("CACHE_TTL_SECONDS", "1.5", false, __penvProblems);
        Double cacheTtlSeconds = null;
        if (__penvRaw_cacheTtlSeconds != null) {
            try {
                cacheTtlSeconds = Double.parseDouble(__penvRaw_cacheTtlSeconds.trim());
            } catch (NumberFormatException __penvE) {
                __penvProblems.add("CACHE_TTL_SECONDS" + " is not a number");
            }
        }
        String __penvRaw_maxRetries = raw("MAX_RETRIES", "", true, __penvProblems);
        Long maxRetries = null;
        if (__penvRaw_maxRetries != null) {
            try {
                maxRetries = Long.parseLong(__penvRaw_maxRetries.trim());
            } catch (NumberFormatException __penvE) {
                __penvProblems.add("MAX_RETRIES" + " is not an integer");
            }
        }
        String __penvRaw_featureBilling = raw("FEATURE_BILLING", "false", false, __penvProblems);
        Boolean featureBilling = __penvRaw_featureBilling == null ? null : flag(__penvRaw_featureBilling);
        if (__penvRaw_featureBilling != null && featureBilling == null) {
            __penvProblems.add("FEATURE_BILLING" + " is not a boolean");
        }
        String __penvRaw_debugTracing = raw("DEBUG_TRACING", "", true, __penvProblems);
        Boolean debugTracing = __penvRaw_debugTracing == null ? null : flag(__penvRaw_debugTracing);
        if (__penvRaw_debugTracing != null && debugTracing == null) {
            __penvProblems.add("DEBUG_TRACING" + " is not a boolean");
        }
        String __penvRaw_alertsEmail = raw("ALERTS_EMAIL", "ops@example.test", false, __penvProblems);
        String alertsEmail = __penvRaw_alertsEmail;
        String __penvRaw_supportNote = raw("SUPPORT_NOTE", "", false, __penvProblems);
        Secret supportNote = __penvRaw_supportNote == null ? null : new Secret(__penvRaw_supportNote);
        String __penvRaw_nextPublicCheckoutToken = raw("NEXT_PUBLIC_CHECKOUT_TOKEN", "", true, __penvProblems);
        Secret nextPublicCheckoutToken = __penvRaw_nextPublicCheckoutToken == null ? null : new Secret(__penvRaw_nextPublicCheckoutToken);
        if (!__penvProblems.isEmpty()) {
            throw new IllegalStateException(String.join("; ", __penvProblems));
        }
        return new Env(
                databaseUrl,
                stripeSecretKey,
                nextPublicAppUrl,
                port,
                nodeEnv,
                planTier,
                cacheTtlSeconds,
                maxRetries,
                featureBilling,
                debugTracing,
                alertsEmail,
                supportNote,
                nextPublicCheckoutToken);
    }
}
