// Generated by penv 1.0.0-test from .env.schema. Do not edit.

package config;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/** Every variable .env.schema declares. {@code Env.load()} reads and checks them. */
public record Env(
        /* Where the service keeps its own rows. */
        Secret databaseUrl,
        Secret stripeSecretKey,
        /* Where the browser is sent back to after a redirect. */
        String nextPublicAppUrl,
        int port,
        String nodeEnv,
        /* The tier this deployment serves. */
        String planTier,
        /* How long a cached value stays fresh. */
        double cacheTtlSeconds,
        long maxRetries,
        boolean featureBilling,
        boolean debugTracing,
        /* Where failures are mailed. */
        String alertsEmail,
        Secret supportNote) {

    /** A value that prints as [redacted]; {@code expose()} returns it. */
    public static final class Secret {
        private final String value;

        public Secret(String value) {
            this.value = value;
        }

        public String expose() {
            return value;
        }

        @Override
        public String toString() {
            return "[redacted]";
        }
    }

    private static String raw(String name, String fallback, boolean required, List<String> problems) {
        String value = System.getenv(name);
        if (value == null || value.isEmpty()) {
            value = fallback;
        }
        if (value == null || value.isEmpty()) {
            if (required) {
                problems.add(name + " is not set; run penv check");
            }
            return null;
        }
        return value;
    }

    private static Boolean flag(String value) {
        switch (value.trim().toLowerCase()) {
            case "1": case "true": case "yes": case "on": return Boolean.TRUE;
            case "0": case "false": case "no": case "off": return Boolean.FALSE;
            default: return null;
        }
    }

    /** Read and check every variable. The exception names each problem, never a value. */
    public static Env load() {
        List<String> problems = new ArrayList<>();
        String databaseUrlRaw = raw("DATABASE_URL", "", true, problems);
        Secret databaseUrl = databaseUrlRaw == null ? null : new Secret(databaseUrlRaw);
        String stripeSecretKeyRaw = raw("STRIPE_SECRET_KEY", "", true, problems);
        Secret stripeSecretKey = stripeSecretKeyRaw == null ? null : new Secret(stripeSecretKeyRaw);
        String nextPublicAppUrlRaw = raw("NEXT_PUBLIC_APP_URL", "http://localhost:3000", false, problems);
        String nextPublicAppUrl = nextPublicAppUrlRaw;
        String portRaw = raw("PORT", "3000", false, problems);
        Integer port = null;
        if (portRaw != null) {
            try {
                int n = Integer.parseInt(portRaw.trim());
                if (n >= 1 && n <= 65535) {
                    port = n;
                } else {
                    problems.add("PORT" + " is not a port");
                }
            } catch (NumberFormatException e) {
                problems.add("PORT" + " is not a port");
            }
        }
        String nodeEnvRaw = raw("NODE_ENV", "development", false, problems);
        String nodeEnv = nodeEnvRaw;
        if (nodeEnv != null && !Set.of("development", "staging", "production").contains(nodeEnv)) {
            problems.add("NODE_ENV" + " is not one of development, staging, production");
            nodeEnv = null;
        }
        String planTierRaw = raw("PLAN_TIER", "", true, problems);
        String planTier = planTierRaw;
        if (planTier != null && !Set.of("free", "pro", "enterprise").contains(planTier)) {
            problems.add("PLAN_TIER" + " is not one of free, pro, enterprise");
            planTier = null;
        }
        String cacheTtlSecondsRaw = raw("CACHE_TTL_SECONDS", "1.5", false, problems);
        Double cacheTtlSeconds = null;
        if (cacheTtlSecondsRaw != null) {
            try {
                cacheTtlSeconds = Double.parseDouble(cacheTtlSecondsRaw.trim());
            } catch (NumberFormatException e) {
                problems.add("CACHE_TTL_SECONDS" + " is not a number");
            }
        }
        String maxRetriesRaw = raw("MAX_RETRIES", "", true, problems);
        Long maxRetries = null;
        if (maxRetriesRaw != null) {
            try {
                maxRetries = Long.parseLong(maxRetriesRaw.trim());
            } catch (NumberFormatException e) {
                problems.add("MAX_RETRIES" + " is not an integer");
            }
        }
        String featureBillingRaw = raw("FEATURE_BILLING", "false", false, problems);
        Boolean featureBilling = featureBillingRaw == null ? null : flag(featureBillingRaw);
        if (featureBillingRaw != null && featureBilling == null) {
            problems.add("FEATURE_BILLING" + " is not a boolean");
        }
        String debugTracingRaw = raw("DEBUG_TRACING", "", true, problems);
        Boolean debugTracing = debugTracingRaw == null ? null : flag(debugTracingRaw);
        if (debugTracingRaw != null && debugTracing == null) {
            problems.add("DEBUG_TRACING" + " is not a boolean");
        }
        String alertsEmailRaw = raw("ALERTS_EMAIL", "ops@example.test", false, problems);
        String alertsEmail = alertsEmailRaw;
        String supportNoteRaw = raw("SUPPORT_NOTE", "", false, problems);
        Secret supportNote = supportNoteRaw == null ? null : new Secret(supportNoteRaw);
        if (!problems.isEmpty()) {
            throw new IllegalStateException(String.join("; ", problems));
        }
        return new Env(
                databaseUrl,
                stripeSecretKey,
                nextPublicAppUrl,
                port,
                nodeEnv,
                planTier,
                cacheTtlSeconds,
                maxRetries,
                featureBilling,
                debugTracing,
                alertsEmail,
                supportNote);
    }
}
