<?php

// Generated by penv 1.0.0-test from .env.schema. Do not edit.

declare(strict_types=1);

namespace App;

/** A value that prints as [redacted]; expose() returns it. */
final class Secret implements \Stringable, \JsonSerializable
{
    public function __construct(private readonly string $value)
    {
    }

    public function expose(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return '[redacted]';
    }

    public function jsonSerialize(): string
    {
        return '[redacted]';
    }

    /** @return array<string, string> */
    public function __debugInfo(): array
    {
        return ['value' => '[redacted]'];
    }
}

/** Every variable .env.schema declares. Env::load() reads and checks them. */
final class Env
{
    public function __construct(
        /** Where the service keeps its own rows. */
        public readonly Secret $databaseUrl,
        public readonly Secret $stripeSecretKey,
        /** Where the browser is sent back to after a redirect. */
        public readonly string $nextPublicAppUrl,
        public readonly int $port,
        public readonly string $nodeEnv,
        /** The tier this deployment serves. */
        public readonly string $planTier,
        /** How long a cached value stays fresh. */
        public readonly float $cacheTtlSeconds,
        public readonly int $maxRetries,
        public readonly bool $featureBilling,
        public readonly bool $debugTracing,
        /** Where failures are mailed. */
        public readonly string $alertsEmail,
        public readonly ?Secret $supportNote,
    ) {
    }

    /** Read and check every variable. The exception names each problem, never a value. */
    public static function load(): self
    {
        $problems = [];
        $raw = static function (string $name, string $default, bool $required) use (&$problems): ?string {
            $value = getenv($name);
            if ($value === false || $value === '') {
                $value = $_ENV[$name] ?? '';
            }
            if ($value === '') {
                $value = $default;
            }
            if ($value === '') {
                if ($required) {
                    $problems[] = "{$name} is not set; run penv check";
                }
                return null;
            }
            return $value;
        };
        $bad = static function (string $name, string $want) use (&$problems): mixed {
            $problems[] = "{$name} is not {$want}";
            return null;
        };
        $databaseUrl = $raw("DATABASE_URL", "", true);
        $databaseUrl = $databaseUrl === null ? null : new Secret($databaseUrl);
        $stripeSecretKey = $raw("STRIPE_SECRET_KEY", "", true);
        $stripeSecretKey = $stripeSecretKey === null ? null : new Secret($stripeSecretKey);
        $nextPublicAppUrl = $raw("NEXT_PUBLIC_APP_URL", "http://localhost:3000", false);
        $port = $raw("PORT", "3000", false);
        if ($port !== null) {
            $n = filter_var($port, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1, 'max_range' => 65535]]);
            $port = $n === false ? $bad("PORT", 'a port') : $n;
        }
        $nodeEnv = $raw("NODE_ENV", "development", false);
        if ($nodeEnv !== null && !in_array($nodeEnv, ["development", "staging", "production"], true)) {
            $nodeEnv = $bad("NODE_ENV", 'one of development, staging, production');
        }
        $planTier = $raw("PLAN_TIER", "", true);
        if ($planTier !== null && !in_array($planTier, ["free", "pro", "enterprise"], true)) {
            $planTier = $bad("PLAN_TIER", 'one of free, pro, enterprise');
        }
        $cacheTtlSeconds = $raw("CACHE_TTL_SECONDS", "1.5", false);
        if ($cacheTtlSeconds !== null) {
            $n = filter_var($cacheTtlSeconds, FILTER_VALIDATE_FLOAT);
            $cacheTtlSeconds = $n === false ? $bad("CACHE_TTL_SECONDS", 'a number') : $n;
        }
        $maxRetries = $raw("MAX_RETRIES", "", true);
        if ($maxRetries !== null) {
            $n = filter_var($maxRetries, FILTER_VALIDATE_INT);
            $maxRetries = $n === false ? $bad("MAX_RETRIES", 'an integer') : $n;
        }
        $featureBilling = $raw("FEATURE_BILLING", "false", false);
        if ($featureBilling !== null) {
            $n = filter_var($featureBilling, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
            $featureBilling = $n === null ? $bad("FEATURE_BILLING", 'a boolean') : $n;
        }
        $debugTracing = $raw("DEBUG_TRACING", "", true);
        if ($debugTracing !== null) {
            $n = filter_var($debugTracing, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
            $debugTracing = $n === null ? $bad("DEBUG_TRACING", 'a boolean') : $n;
        }
        $alertsEmail = $raw("ALERTS_EMAIL", "ops@example.test", false);
        $supportNote = $raw("SUPPORT_NOTE", "", false);
        $supportNote = $supportNote === null ? null : new Secret($supportNote);
        if ($problems !== []) {
            throw new \RuntimeException(implode('; ', $problems));
        }

        return new self(
            databaseUrl: $databaseUrl,
            stripeSecretKey: $stripeSecretKey,
            nextPublicAppUrl: $nextPublicAppUrl,
            port: $port,
            nodeEnv: $nodeEnv,
            planTier: $planTier,
            cacheTtlSeconds: $cacheTtlSeconds,
            maxRetries: $maxRetries,
            featureBilling: $featureBilling,
            debugTracing: $debugTracing,
            alertsEmail: $alertsEmail,
            supportNote: $supportNote,
        );
    }
}
