<?php

// Generated by penv 1.0.0-test from .env.schema. Do not edit.

declare(strict_types=1);

namespace App;

/** A value that prints as [redacted]; expose() returns it. */
final class Secret implements \Stringable, \JsonSerializable
{
    public function __construct(private readonly string $value)
    {
    }

    public function expose(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return '[redacted]';
    }

    public function jsonSerialize(): string
    {
        return '[redacted]';
    }

    /** @return array<string, string> */
    public function __debugInfo(): array
    {
        return ['value' => '[redacted]'];
    }
}

/** Every variable .env.schema declares. Env::load() reads and checks them. */
final class Env
{
    public function __construct(
        /** Where the service keeps its own rows. */
        public readonly Secret $databaseUrl,
        public readonly Secret $stripeSecretKey,
        /** Where the browser is sent back to after a redirect. */
        public readonly string $nextPublicAppUrl,
        public readonly int $port,
        public readonly string $nodeEnv,
        /** The tier this deployment serves. */
        public readonly string $planTier,
        /** How long a cached value stays fresh. */
        public readonly float $cacheTtlSeconds,
        public readonly int $maxRetries,
        public readonly bool $featureBilling,
        public readonly bool $debugTracing,
        /** Where failures are mailed. */
        public readonly string $alertsEmail,
        public readonly ?Secret $supportNote,
        /** Built from the secret, so its prefix does not make it safe to inline. */
        public readonly Secret $nextPublicCheckoutToken,
    ) {
    }

    /** Read and check every variable. The exception names each problem, never a value. */
    public static function load(): self
    {
        $__penvProblems = [];
        $__penvRaw = static function (string $name, string $default, bool $required) use (&$__penvProblems): ?string {
            $value = getenv($name);
            if ($value === false || $value === '') {
                $value = $_ENV[$name] ?? '';
            }
            if ($value === '') {
                $value = $default;
            }
            if ($value === '') {
                if ($required) {
                    $__penvProblems[] = "{$name} is not set; run penv check";
                }
                return null;
            }
            return $value;
        };
        $__penvBad = static function (string $name, string $want) use (&$__penvProblems): mixed {
            $__penvProblems[] = "{$name} is not {$want}";
            return null;
        };
        $databaseUrl = $__penvRaw('DATABASE_URL', '', true);
        $databaseUrl = $databaseUrl === null ? null : new Secret($databaseUrl);
        $stripeSecretKey = $__penvRaw('STRIPE_SECRET_KEY', '', true);
        $stripeSecretKey = $stripeSecretKey === null ? null : new Secret($stripeSecretKey);
        $nextPublicAppUrl = $__penvRaw('NEXT_PUBLIC_APP_URL', 'http://localhost:3000', false);
        $port = $__penvRaw('PORT', '3000', false);
        if ($port !== null) {
            $__penvN = filter_var($port, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1, 'max_range' => 65535]]);
            $port = $__penvN === false ? $__penvBad('PORT', 'a port') : $__penvN;
        }
        $nodeEnv = $__penvRaw('NODE_ENV', 'development', false);
        if ($nodeEnv !== null && !in_array($nodeEnv, ['development', 'staging', 'production'], true)) {
            $nodeEnv = $__penvBad('NODE_ENV', 'one of development, staging, production');
        }
        $planTier = $__penvRaw('PLAN_TIER', '', true);
        if ($planTier !== null && !in_array($planTier, ['free', 'pro', 'enterprise'], true)) {
            $planTier = $__penvBad('PLAN_TIER', 'one of free, pro, enterprise');
        }
        $cacheTtlSeconds = $__penvRaw('CACHE_TTL_SECONDS', '1.5', false);
        if ($cacheTtlSeconds !== null) {
            $__penvN = filter_var($cacheTtlSeconds, FILTER_VALIDATE_FLOAT);
            $cacheTtlSeconds = $__penvN === false ? $__penvBad('CACHE_TTL_SECONDS', 'a number') : $__penvN;
        }
        $maxRetries = $__penvRaw('MAX_RETRIES', '', true);
        if ($maxRetries !== null) {
            $__penvN = filter_var($maxRetries, FILTER_VALIDATE_INT);
            $maxRetries = $__penvN === false ? $__penvBad('MAX_RETRIES', 'an integer') : $__penvN;
        }
        $featureBilling = $__penvRaw('FEATURE_BILLING', 'false', false);
        if ($featureBilling !== null) {
            $__penvN = filter_var($featureBilling, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
            $featureBilling = $__penvN === null ? $__penvBad('FEATURE_BILLING', 'a boolean') : $__penvN;
        }
        $debugTracing = $__penvRaw('DEBUG_TRACING', '', true);
        if ($debugTracing !== null) {
            $__penvN = filter_var($debugTracing, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
            $debugTracing = $__penvN === null ? $__penvBad('DEBUG_TRACING', 'a boolean') : $__penvN;
        }
        $alertsEmail = $__penvRaw('ALERTS_EMAIL', 'ops@example.test', false);
        $supportNote = $__penvRaw('SUPPORT_NOTE', '', false);
        $supportNote = $supportNote === null ? null : new Secret($supportNote);
        $nextPublicCheckoutToken = $__penvRaw('NEXT_PUBLIC_CHECKOUT_TOKEN', '', true);
        $nextPublicCheckoutToken = $nextPublicCheckoutToken === null ? null : new Secret($nextPublicCheckoutToken);
        if ($__penvProblems !== []) {
            throw new \RuntimeException(implode('; ', $__penvProblems));
        }

        return new self(
            databaseUrl: $databaseUrl,
            stripeSecretKey: $stripeSecretKey,
            nextPublicAppUrl: $nextPublicAppUrl,
            port: $port,
            nodeEnv: $nodeEnv,
            planTier: $planTier,
            cacheTtlSeconds: $cacheTtlSeconds,
            maxRetries: $maxRetries,
            featureBilling: $featureBilling,
            debugTracing: $debugTracing,
            alertsEmail: $alertsEmail,
            supportNote: $supportNote,
            nextPublicCheckoutToken: $nextPublicCheckoutToken,
        );
    }
}
