//! Generated by penv 1.0.0-test from .env.schema. Do not edit.
//!
//! `Env::load()` reads and checks every variable .env.schema declares. A field
//! holding a secret has type `Secret`, which prints as `[redacted]`.

#![allow(dead_code)]

use std::fmt;

/// A value that prints as `[redacted]`; `expose` returns it.
#[derive(Clone, Default, PartialEq, Eq)]
pub struct Secret(String);

impl Secret {
    /// The secret itself.
    pub fn expose(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for Secret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("[redacted]")
    }
}

impl fmt::Display for Secret {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("[redacted]")
    }
}

/// Every variable .env.schema declares.
#[derive(Debug, Clone)]
pub struct Env {
    /// Where the service keeps its own rows.
    pub database_url: Secret,
    pub stripe_secret_key: Secret,
    /// Where the browser is sent back to after a redirect.
    pub next_public_app_url: String,
    pub port: u16,
    pub node_env: String,
    /// The tier this deployment serves.
    pub plan_tier: String,
    /// How long a cached value stays fresh.
    pub cache_ttl_seconds: f64,
    pub max_retries: i64,
    pub feature_billing: bool,
    pub debug_tracing: bool,
    /// Where failures are mailed.
    pub alerts_email: String,
    pub support_note: Option<Secret>,
}

fn raw(name: &str, default: &str, required: bool, problems: &mut Vec<String>) -> Option<String> {
    let value = std::env::var(name).ok().filter(|v| !v.is_empty());
    let value = value.or_else(|| (!default.is_empty()).then(|| default.to_string()));
    if value.is_none() && required {
        problems.push(format!("{name} is not set; run penv check"));
    }
    value
}

fn parsed<T>(name: &str, want: &str, value: Option<String>, parse: impl Fn(&str) -> Option<T>, problems: &mut Vec<String>) -> Option<T> {
    let value = value?;
    let out = parse(&value);
    if out.is_none() {
        problems.push(format!("{name} is not {want}"));
    }
    out
}

fn flag(v: &str) -> Option<bool> {
    match v.trim().to_ascii_lowercase().as_str() {
        "1" | "true" | "yes" | "on" => Some(true),
        "0" | "false" | "no" | "off" => Some(false),
        _ => None,
    }
}

impl Env {
    /// Read and check every variable. The error names each problem, never a value.
    pub fn load() -> Result<Env, String> {
        let mut problems = Vec::new();
        let database_url = raw("DATABASE_URL", "", true, &mut problems);
        let database_url = database_url.map(Secret);
        let stripe_secret_key = raw("STRIPE_SECRET_KEY", "", true, &mut problems);
        let stripe_secret_key = stripe_secret_key.map(Secret);
        let next_public_app_url = raw("NEXT_PUBLIC_APP_URL", "http://localhost:3000", false, &mut problems);
        let port = raw("PORT", "3000", false, &mut problems);
        let port = parsed("PORT", "a port", port, |v| v.parse::<u16>().ok().filter(|p| *p > 0), &mut problems);
        let node_env = raw("NODE_ENV", "development", false, &mut problems);
        let node_env = parsed("NODE_ENV", "one of development, staging, production", node_env, |v| ["development", "staging", "production"].contains(&v).then(|| v.to_string()), &mut problems);
        let plan_tier = raw("PLAN_TIER", "", true, &mut problems);
        let plan_tier = parsed("PLAN_TIER", "one of free, pro, enterprise", plan_tier, |v| ["free", "pro", "enterprise"].contains(&v).then(|| v.to_string()), &mut problems);
        let cache_ttl_seconds = raw("CACHE_TTL_SECONDS", "1.5", false, &mut problems);
        let cache_ttl_seconds = parsed("CACHE_TTL_SECONDS", "a number", cache_ttl_seconds, |v| v.parse::<f64>().ok(), &mut problems);
        let max_retries = raw("MAX_RETRIES", "", true, &mut problems);
        let max_retries = parsed("MAX_RETRIES", "an integer", max_retries, |v| v.parse::<i64>().ok(), &mut problems);
        let feature_billing = raw("FEATURE_BILLING", "false", false, &mut problems);
        let feature_billing = parsed("FEATURE_BILLING", "a boolean", feature_billing, flag, &mut problems);
        let debug_tracing = raw("DEBUG_TRACING", "", true, &mut problems);
        let debug_tracing = parsed("DEBUG_TRACING", "a boolean", debug_tracing, flag, &mut problems);
        let alerts_email = raw("ALERTS_EMAIL", "ops@example.test", false, &mut problems);
        let support_note = raw("SUPPORT_NOTE", "", false, &mut problems);
        let support_note = support_note.map(Secret);
        if !problems.is_empty() {
            return Err(problems.join("; "));
        }
        Ok(Env {
            database_url: database_url.unwrap_or_default(),
            stripe_secret_key: stripe_secret_key.unwrap_or_default(),
            next_public_app_url: next_public_app_url.unwrap_or_default(),
            port: port.unwrap_or_default(),
            node_env: node_env.unwrap_or_default(),
            plan_tier: plan_tier.unwrap_or_default(),
            cache_ttl_seconds: cache_ttl_seconds.unwrap_or_default(),
            max_retries: max_retries.unwrap_or_default(),
            feature_billing: feature_billing.unwrap_or_default(),
            debug_tracing: debug_tracing.unwrap_or_default(),
            alerts_email: alerts_email.unwrap_or_default(),
            support_note,
        })
    }
}
