// Generated by penv 1.0.0-test from .env.schema. Do not edit.

export const env = {
  /** Where the service keeps its own rows. */
  DATABASE_URL: process.env.DATABASE_URL as string,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY as string,
  /** Where the browser is sent back to after a redirect. */
  NEXT_PUBLIC_APP_URL: (process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000") as string,
  PORT: Number(process.env.PORT ?? "3000"),
  NODE_ENV: (process.env.NODE_ENV ?? "development") as "development" | "staging" | "production",
  /** The tier this deployment serves. */
  PLAN_TIER: process.env.PLAN_TIER as "free" | "pro" | "enterprise",
  /** How long a cached value stays fresh. */
  CACHE_TTL_SECONDS: Number(process.env.CACHE_TTL_SECONDS ?? "1.5"),
  MAX_RETRIES: Number(process.env.MAX_RETRIES),
  FEATURE_BILLING: (process.env.FEATURE_BILLING ?? "false") === "true",
  DEBUG_TRACING: process.env.DEBUG_TRACING === "true",
  /** Where failures are mailed. */
  ALERTS_EMAIL: (process.env.ALERTS_EMAIL ?? "ops@example.test") as string,
  SUPPORT_NOTE: process.env.SUPPORT_NOTE as string | undefined,
} as const;

export type Env = typeof env;

export const envSchema = {
  "~standard": {
    version: 1,
    vendor: "penv",
    validate: (input: unknown) => {
      const seen = (input ?? {}) as Record<string, unknown>;
      const issues: { message: string; path: [string] }[] = [];
      const is = {
        number: (v: string) => Number.isFinite(Number(v)),
        integer: (v: string) => Number.isInteger(Number(v)),
        port: (v: string) => Number.isInteger(Number(v)) && Number(v) >= 1 && Number(v) <= 65535,
        boolean: (v: string) => v === "true" || v === "false",
        url: (v: string) => { try { new URL(v); return true; } catch { return false; } },
        email: (v: string) => { const at = v.indexOf("@"); return at > 0 && at < v.length - 1 && at === v.lastIndexOf("@"); },
      };
      if (seen["DATABASE_URL"] === undefined || seen["DATABASE_URL"] === "") {
        issues.push({ message: "DATABASE_URL is required", path: ["DATABASE_URL"] });
      }
      if (seen["DATABASE_URL"] !== undefined && seen["DATABASE_URL"] !== "" && !is.url(String(seen["DATABASE_URL"]))) {
        issues.push({ message: "DATABASE_URL must be a url", path: ["DATABASE_URL"] });
      }
      if (seen["STRIPE_SECRET_KEY"] === undefined || seen["STRIPE_SECRET_KEY"] === "") {
        issues.push({ message: "STRIPE_SECRET_KEY is required", path: ["STRIPE_SECRET_KEY"] });
      }
      if (seen["NEXT_PUBLIC_APP_URL"] !== undefined && seen["NEXT_PUBLIC_APP_URL"] !== "" && !is.url(String(seen["NEXT_PUBLIC_APP_URL"]))) {
        issues.push({ message: "NEXT_PUBLIC_APP_URL must be a url", path: ["NEXT_PUBLIC_APP_URL"] });
      }
      if (seen["PORT"] !== undefined && seen["PORT"] !== "" && !is.port(String(seen["PORT"]))) {
        issues.push({ message: "PORT must be a port between 1 and 65535", path: ["PORT"] });
      }
      if (seen["NODE_ENV"] !== undefined && seen["NODE_ENV"] !== "" && !["development","staging","production"].includes(String(seen["NODE_ENV"]))) {
        issues.push({ message: "NODE_ENV must be one of development, staging, production", path: ["NODE_ENV"] });
      }
      if (seen["PLAN_TIER"] === undefined || seen["PLAN_TIER"] === "") {
        issues.push({ message: "PLAN_TIER is required", path: ["PLAN_TIER"] });
      }
      if (seen["PLAN_TIER"] !== undefined && seen["PLAN_TIER"] !== "" && !["free","pro","enterprise"].includes(String(seen["PLAN_TIER"]))) {
        issues.push({ message: "PLAN_TIER must be one of free, pro, enterprise", path: ["PLAN_TIER"] });
      }
      if (seen["CACHE_TTL_SECONDS"] !== undefined && seen["CACHE_TTL_SECONDS"] !== "" && !is.number(String(seen["CACHE_TTL_SECONDS"]))) {
        issues.push({ message: "CACHE_TTL_SECONDS must be a number", path: ["CACHE_TTL_SECONDS"] });
      }
      if (seen["MAX_RETRIES"] === undefined || seen["MAX_RETRIES"] === "") {
        issues.push({ message: "MAX_RETRIES is required", path: ["MAX_RETRIES"] });
      }
      if (seen["MAX_RETRIES"] !== undefined && seen["MAX_RETRIES"] !== "" && !is.integer(String(seen["MAX_RETRIES"]))) {
        issues.push({ message: "MAX_RETRIES must be a whole number", path: ["MAX_RETRIES"] });
      }
      if (seen["FEATURE_BILLING"] !== undefined && seen["FEATURE_BILLING"] !== "" && !is.boolean(String(seen["FEATURE_BILLING"]))) {
        issues.push({ message: "FEATURE_BILLING must be true or false", path: ["FEATURE_BILLING"] });
      }
      if (seen["DEBUG_TRACING"] === undefined || seen["DEBUG_TRACING"] === "") {
        issues.push({ message: "DEBUG_TRACING is required", path: ["DEBUG_TRACING"] });
      }
      if (seen["DEBUG_TRACING"] !== undefined && seen["DEBUG_TRACING"] !== "" && !is.boolean(String(seen["DEBUG_TRACING"]))) {
        issues.push({ message: "DEBUG_TRACING must be true or false", path: ["DEBUG_TRACING"] });
      }
      if (seen["ALERTS_EMAIL"] !== undefined && seen["ALERTS_EMAIL"] !== "" && !is.email(String(seen["ALERTS_EMAIL"]))) {
        issues.push({ message: "ALERTS_EMAIL must be an email address", path: ["ALERTS_EMAIL"] });
      }
      return issues.length > 0 ? { issues } : { value: env };
    },
  },
} as const;