// Generated by penv 1.0.0-test from .env.schema. Do not edit.

// Server keys are read here, by computed name, never as process.env.NAME: a
// bundler inlines only the literal form, so no build can copy these values into
// client code. In a runtime with no server environment (a browser) it throws.
const read = (name: string): string | undefined => {
  const g = globalThis as {
    process?: { env?: Record<string, string | undefined> };
    Deno?: { env: { get(name: string): string | undefined } };
    Netlify?: { env: { get(name: string): string | undefined } };
  };
  if (g.process?.env) return g.process.env[name];
  if (g.Deno?.env) return g.Deno.env.get(name);
  if (g.Netlify?.env) return g.Netlify.env.get(name);
  throw new Error(`${name} is server-only, and this runtime has no server environment.`);
};
// Public keys are written as a literal the bundler replaces. Where nothing
// replaced it and the runtime has no process global (an edge runtime, a Worker), the
// literal would throw, so the key is read the computed way, or is undefined.
const inlined = (literal: () => string | undefined, name: string): string | undefined => {
  try {
    const value = literal();
    if (value !== undefined) return value;
  } catch {
    // no process global here
  }
  try {
    return read(name);
  } catch {
    return undefined;
  }
};

// Masks this app's own secret values in what it logs and what it serves, in
// any server runtime (Node, Bun, Deno, edge, Workers), with no wrapper process:
// console methods (and any a log shipper installs later) and the Response
// constructor. Two characters kept, the rest replaced. Off with
// [targets.ts.options] mask = false.
(() => {
  const g = globalThis as { window?: unknown; __penvMask?: boolean; Response?: typeof Response };
  if (g.window !== undefined || g.__penvMask) return;
  let values: string[];
  try {
    values = [
      read("DATABASE_URL"),
      read("STRIPE_SECRET_KEY"),
      read("PORT"),
      read("NODE_ENV"),
      read("DEBUG_TRACING"),
      read("SUPPORT_NOTE"),
    ].filter((v): v is string => typeof v === "string" && v.length >= 4);
  } catch {
    return;
  }
  if (values.length === 0) return;
  g.__penvMask = true;
  const b64 = (v: string) => {
    try {
      return btoa(String.fromCharCode(...new TextEncoder().encode(v)));
    } catch {
      return "";
    }
  };
  const forms = [...new Set(values.flatMap((v) => [v, encodeURIComponent(v), b64(v), JSON.stringify(v).slice(1, -1)]))]
    .filter((f) => f.length >= 4)
    .sort((a, b) => b.length - a.length);
  const mask = (text: string) => {
    let out = text;
    for (const f of forms) if (out.includes(f)) out = out.split(f).join(f.slice(0, 2) + "*".repeat(f.length - 2));
    return out;
  };
  const maskArg = (a: unknown): unknown => {
    if (typeof a === "string") return mask(a);
    if (a && typeof a === "object") {
      try {
        const json = JSON.stringify(a);
        if (typeof json === "string" && mask(json) !== json) return mask(json);
      } catch {
        // not serialisable: printed as it is
      }
    }
    return a;
  };
  const guard = (fn: unknown) => {
    if (typeof fn !== "function" || (fn as { __penv?: boolean }).__penv) return fn;
    const wrapped = function (this: unknown, ...args: unknown[]) {
      return (fn as (...a: unknown[]) => unknown).apply(this, args.map(maskArg));
    };
    (wrapped as { __penv?: boolean }).__penv = true;
    return wrapped;
  };
  const target = console as unknown as Record<string, unknown>;
  for (const level of ["log", "info", "warn", "error", "debug", "trace"]) {
    let current = guard(target[level]);
    try {
      Object.defineProperty(console, level, {
        configurable: true,
        get: () => current,
        set: (fn: unknown) => {
          current = guard(fn);
        },
      });
    } catch {
      target[level] = current;
    }
  }
  const Original = g.Response;
  if (typeof Original === "function") {
    type Body = ConstructorParameters<typeof Response>[0];
    type Init = ConstructorParameters<typeof Response>[1];
    class Masked extends Original {
      constructor(body?: Body, init?: Init) {
        super(typeof body === "string" ? mask(body) : body, init);
      }
            static override json(data: unknown, init?: Init) {
        const headers = new Headers(init?.headers);
        if (!headers.has("content-type")) headers.set("content-type", "application/json");
        return new Masked(JSON.stringify(data), { ...init, headers });
      }
    }
    g.Response = Masked;
  }
})();

export const env = {
  /** Where the service keeps its own rows. */
  get DATABASE_URL() {
    return read("DATABASE_URL") as string;
  },
  get STRIPE_SECRET_KEY() {
    return read("STRIPE_SECRET_KEY") as string;
  },
  /** Where the browser is sent back to after a redirect. */
  get NEXT_PUBLIC_APP_URL() {
    return (inlined(() => process.env.NEXT_PUBLIC_APP_URL, "NEXT_PUBLIC_APP_URL") ?? "http://localhost:3000") as string;
  },
  get PORT() {
    return Number(read("PORT") ?? "3000");
  },
  get NODE_ENV() {
    return (read("NODE_ENV") ?? "development") as "development" | "staging" | "production";
  },
  /** The tier this deployment serves. */
  get PLAN_TIER() {
    return read("PLAN_TIER") as "free" | "pro" | "enterprise";
  },
  /** How long a cached value stays fresh. */
  get CACHE_TTL_SECONDS() {
    return Number(read("CACHE_TTL_SECONDS") ?? "1.5");
  },
  get MAX_RETRIES() {
    return Number(read("MAX_RETRIES"));
  },
  get FEATURE_BILLING() {
    return (read("FEATURE_BILLING") ?? "false") === "true";
  },
  get DEBUG_TRACING() {
    return read("DEBUG_TRACING") === "true";
  },
  /** Where failures are mailed. */
  get ALERTS_EMAIL() {
    return (read("ALERTS_EMAIL") ?? "ops@example.test") as string;
  },
  get SUPPORT_NOTE() {
    return read("SUPPORT_NOTE") as string | undefined;
  },
};

export type Env = typeof env;

export const envSchema = {
  "~standard": {
    version: 1,
    vendor: "penv",
    validate: (input: unknown) => {
      const seen = (input ?? {}) as Record<string, unknown>;
      const issues: { message: string; path: [string] }[] = [];
      const is = {
        number: (v: string) => Number.isFinite(Number(v)),
        integer: (v: string) => Number.isInteger(Number(v)),
        port: (v: string) => Number.isInteger(Number(v)) && Number(v) >= 1 && Number(v) <= 65535,
        boolean: (v: string) => v === "true" || v === "false",
        url: (v: string) => { try { new URL(v); return true; } catch { return false; } },
        email: (v: string) => { const at = v.indexOf("@"); return at > 0 && at < v.length - 1 && at === v.lastIndexOf("@"); },
      };
      if (seen["DATABASE_URL"] === undefined || seen["DATABASE_URL"] === "") {
        issues.push({ message: "DATABASE_URL is required", path: ["DATABASE_URL"] });
      }
      if (seen["DATABASE_URL"] !== undefined && seen["DATABASE_URL"] !== "" && !is.url(String(seen["DATABASE_URL"]))) {
        issues.push({ message: "DATABASE_URL must be a url", path: ["DATABASE_URL"] });
      }
      if (seen["STRIPE_SECRET_KEY"] === undefined || seen["STRIPE_SECRET_KEY"] === "") {
        issues.push({ message: "STRIPE_SECRET_KEY is required", path: ["STRIPE_SECRET_KEY"] });
      }
      if (seen["NEXT_PUBLIC_APP_URL"] !== undefined && seen["NEXT_PUBLIC_APP_URL"] !== "" && !is.url(String(seen["NEXT_PUBLIC_APP_URL"]))) {
        issues.push({ message: "NEXT_PUBLIC_APP_URL must be a url", path: ["NEXT_PUBLIC_APP_URL"] });
      }
      if (seen["PORT"] !== undefined && seen["PORT"] !== "" && !is.port(String(seen["PORT"]))) {
        issues.push({ message: "PORT must be a port between 1 and 65535", path: ["PORT"] });
      }
      if (seen["NODE_ENV"] !== undefined && seen["NODE_ENV"] !== "" && !["development","staging","production"].includes(String(seen["NODE_ENV"]))) {
        issues.push({ message: "NODE_ENV must be one of development, staging, production", path: ["NODE_ENV"] });
      }
      if (seen["PLAN_TIER"] === undefined || seen["PLAN_TIER"] === "") {
        issues.push({ message: "PLAN_TIER is required", path: ["PLAN_TIER"] });
      }
      if (seen["PLAN_TIER"] !== undefined && seen["PLAN_TIER"] !== "" && !["free","pro","enterprise"].includes(String(seen["PLAN_TIER"]))) {
        issues.push({ message: "PLAN_TIER must be one of free, pro, enterprise", path: ["PLAN_TIER"] });
      }
      if (seen["CACHE_TTL_SECONDS"] !== undefined && seen["CACHE_TTL_SECONDS"] !== "" && !is.number(String(seen["CACHE_TTL_SECONDS"]))) {
        issues.push({ message: "CACHE_TTL_SECONDS must be a number", path: ["CACHE_TTL_SECONDS"] });
      }
      if (seen["MAX_RETRIES"] === undefined || seen["MAX_RETRIES"] === "") {
        issues.push({ message: "MAX_RETRIES is required", path: ["MAX_RETRIES"] });
      }
      if (seen["MAX_RETRIES"] !== undefined && seen["MAX_RETRIES"] !== "" && !is.integer(String(seen["MAX_RETRIES"]))) {
        issues.push({ message: "MAX_RETRIES must be a whole number", path: ["MAX_RETRIES"] });
      }
      if (seen["FEATURE_BILLING"] !== undefined && seen["FEATURE_BILLING"] !== "" && !is.boolean(String(seen["FEATURE_BILLING"]))) {
        issues.push({ message: "FEATURE_BILLING must be true or false", path: ["FEATURE_BILLING"] });
      }
      if (seen["DEBUG_TRACING"] === undefined || seen["DEBUG_TRACING"] === "") {
        issues.push({ message: "DEBUG_TRACING is required", path: ["DEBUG_TRACING"] });
      }
      if (seen["DEBUG_TRACING"] !== undefined && seen["DEBUG_TRACING"] !== "" && !is.boolean(String(seen["DEBUG_TRACING"]))) {
        issues.push({ message: "DEBUG_TRACING must be true or false", path: ["DEBUG_TRACING"] });
      }
      if (seen["ALERTS_EMAIL"] !== undefined && seen["ALERTS_EMAIL"] !== "" && !is.email(String(seen["ALERTS_EMAIL"]))) {
        issues.push({ message: "ALERTS_EMAIL must be an email address", path: ["ALERTS_EMAIL"] });
      }
      return issues.length > 0 ? { issues } : { value: env };
    },
  },
} as const;